let dialog = {
    "Piety: I recognise that pretty face. Grand Arena, Theopolis. I've a future in mind that I think would suit you, Duelist.": "Brutus, Lord Incarcerator",
    "Piety: Curious. It moves like a killer yet reeks of thaumaturgy. Would that I could observe you more closely, my mysterious Shadow.": "Brutus, Lord Incarcerator",
    "Piety: Your answer's here, heretic. In Wraeclast. But I don't think you'll like it very much.": "Brutus, Lord Incarcerator",
    "Piety: Ignorance brought you here, sister. To the one place where your talents are free to grow and be truly feared.": "Brutus, Lord Incarcerator",
    "Piety: Your brawn is about to meet its match, brute. Give the Warden my regards.": "Brutus, Lord Incarcerator",
    "Piety: Quite sure of yourself, aren't you, huntress? The Warden enjoys the taste of overconfidence.": "Brutus, Lord Incarcerator",
    "Piety: The wonder child? I saw you perform for Dominus, girl. You were very good. Good enough to survive Wraeclast? We'll see.": "Brutus, Lord Incarcerator",
    "Merveil: This is love's true face!": "Merveil, the Siren",
    "Piety: So you've chosen to end our affair, Duelist? I shall cherish your memory.": "Piety",
    "Piety: It's been a grand experiment, Shadow. Time we saw the results.": "Piety",
    "Piety: Your conviction drives you, heretic. But have you thought what it might drive others to do in return?": "Piety",
    "Piety: Of all the worlds you could have conquered, you had to choose mine. Such power wasted on a feeble imagination.": "Piety",
    "Piety: You've done your Ancestors proud, Karui. Now here's your warrior's death!": "Piety",
    "Piety: I have pursued a greater existence for us all. What have you ever done but serve yourself?": "Piety",
    "Piety: I see it now, wonder child. You are but a reflection. A mirror that I must now break.": "Piety",
    "Dominus: You'd bite the master that called you here, Witch?": "Dominus, High Templar",
    "Dominus: I exiled an animal. Now you almost resemble a man, Karui.": "Dominus, High Templar",
    "Dominus: It is woman's purpose to tempt and try the will of man.": "Dominus, High Templar",
    "Dominus: I've dealt with far darker shadows than you, exile.": "Dominus, High Templar",
    "Dominus: Welcome to the greatest of arenas, Duelist. God is watching.": "Dominus, High Templar",
    "Dominus: Exile has tested you, my brother. Now let's see what God has to say.": "Dominus, High Templar",
    "Dominus: I offered the gift of exile and you used it to reinvent yourself. I couldn't wish for a more potent instrument.": "Dominus, High Templar",
    "Dominus: This world is an illusion, exile.": "Dominus, Ascendant",
    "King Kaom: The Black Spirit walks amongst us.": "King Kaom",
    "King Kaom: Death will save you!": "King Kaom",
    "King Kaom: Join your Ancestors!": "King Kaom",
    "King Kaom: Another head for my belt.": "King Kaom",
    "Daresso: A King of Swords is nothing if he cannot defend his crown.": "Daresso, King of Swords",
    "Malachai: I have been expecting you, Witch. You and I are about to create the most beautiful of Nightmares together. Will you go to bed now, little girl? Or do I need to tuck you in?": "Malachai, The Nightmare",
    "Malachai: What a pleasure to finally meet you, Duelist. You and I will create the most beautiful of Nightmares together. Let us bathe you in blood, Duelist. So that this world might be bathed in glory!": "Malachai, The Nightmare",
    "Malachai: I actually find myself admiring you in this moment, Templar. You and I will create the most beautiful of Nightmares together. Rather the hallmark of God, isn't it? Let me show you what a real god can do!": "Malachai, The Nightmare",
    "Malachai: I admire you in this moment, Ranger. You and I will create the most beautiful of Nightmares together. Creation... usually the concern of Nature, isn't it? Not anymore.": "Malachai, The Nightmare",
    "Malachai: I've followed your performance, my anti-hero of hubris, and I've very much enjoyed it. Now you and I will create the most nightmarish of finales together. We're going to make your death really count for something.": "Malachai, The Nightmare",
    "Malachai: In this moment, you and I will create the most beautiful of Nightmares together. Creation... rather the realm of the Gods, isn't it? Bow your head to your one, true god!": "Malachai, The Nightmare",
    "Malachai: You could not be more perfect, Scion. So now it is up to us to commit one final act of creation. A single death that will mark the rebirth of an entire world!": "Malachai, The Nightmare",
    "Avarius: The world must be cleansed of impurity.": "High Templar Avarius",
    "Sin: Innocence!": "Sin",
    "Sin: The flame of hope may flicker but it cannot be extinguished!": "Defeat",
    "Tukohama: Let me teach you the laws of war.": "Minor God",
    "Sin: Tukohama!": "Sin",
    "Sin: Abberath!": "Sin",
    "Sin: Ryslatha!": "Sin",
    "Nessa: So strong, so dedicated. A man like you would never disappoint a lady in need. You're a gift, don't you see? A sumptuous feast for his majesty on his wedding day. Really, we are both so touched by your generosity.": "Tsoagoth, The Brine King",
    "Nessa: So courageous, such a fine example of womanhood. I simply knew you wouldn't disappoint me. Or my husband. You see, his majesty could never be satiated on his wedding day by one bride alone. Thank you, my new sister. I shall always treasure your company.": "Tsoagoth, The Brine King",
    "Sin: Tsoagoth!": "Sin",
    "Sin: Ralakesh!": "Sin",
    "Sin: Gruthkul!": "Sin",
    "Silk: My bride has arrived, exile! I hope you brought a wedding gift!": "Arakaali, Spinner of Shadows",
    "Sin: Arakaali!": "Sin",
    "Sin: Yugul!": "Sin",
    "Sin: Solaris! Lunaris!": "Sin",
    "Sin: Daughter!": "Sin",
    "Sin: My love...": "Sin",
    "Sin: I shall strike you down!": "Kitava, the Insatiable",
    "Sin: May a new dawn arise!": "Sin"
}

module.exports = {
	dialog: dialog
}
