let soundtrack = {
	"tracks": [
	    {"name": "options", "location": "https://www.youtube.com/watch?v=AoTDngh-d2E"},
	    {"name": "rogue_encampment", "location": "https://www.youtube.com/watch?v=t1Zf9w--VhM"},
	    {"name": "wild", "location": "https://www.youtube.com/watch?v=LEKoC5s6150"},
	    {"name": "tristram", "location": "https://www.youtube.com/watch?v=8nl4KeCiEtQ"},
	    {"name": "monastery", "location": "https://www.youtube.com/watch?v=HvMeIJOqrhg"},
	    {"name": "caves", "location": "https://www.youtube.com/watch?v=0Zd0zDnTCoM"},
	    {"name": "crypt", "location": "https://www.youtube.com/watch?v=U2eHs-C1828"},

	    {"name": "lut_gholein", "location": "https://www.youtube.com/watch?v=OmdXk3jJsB0"},
	    {"name": "desert", "location": "https://www.youtube.com/watch?v=mseOvWsn55w"},
	    {"name": "valley", "location": "https://www.youtube.com/watch?v=PYe_Dd48Mcs"},
	    {"name": "sewer", "location": "https://www.youtube.com/watch?v=LH_F9SshwIw"},
	    {"name": "tombs", "location": "https://www.youtube.com/watch?v=YnSKVIH4_3k"},
	    {"name": "lair", "location": "https://www.youtube.com/watch?v=MbyhMeB10t8"},
	    {"name": "harem", "location": "https://www.youtube.com/watch?v=ub_Igr_L-rw"},
	    {"name": "sanctuary", "location": "https://www.youtube.com/watch?v=CoTRxDhyzms"},

	    {"name": "kurast_docks", "location": "https://www.youtube.com/watch?v=OehozBDOF_Q"},
	    {"name": "jungle", "location": "https://www.youtube.com/watch?v=3ZXLsl2qazQ"},
	    {"name": "kurast", "location": "https://www.youtube.com/watch?v=bwPNeWUSjKQ"},
	    {"name": "spider", "location": "https://www.youtube.com/watch?v=Ocp7GyhyeTo"},
	    {"name": "kurast_sewers", "location": "https://www.youtube.com/watch?v=AvfZRdGZstA"},

	    {"name": "pandemonium_fortress", "location": "https://www.youtube.com/watch?v=v2XzZZI0f48"},
	    {"name": "mesa", "location": "https://www.youtube.com/watch?v=qlIBDL_W8xo"},
	    {"name": "diablo", "location": "https://www.youtube.com/watch?v=n041TsHeJi8"},

	    {"name": "intro", "location": "https://www.youtube.com/watch?v=LngkyTYbLrk"},
	    {"name": "harrogath", "location": "https://www.youtube.com/watch?v=layjWs2IpS4"},
	    {"name": "siege", "location": "https://www.youtube.com/watch?v=HylopY97ALc"},
	    {"name": "ice_caves", "location": "https://www.youtube.com/watch?v=hMppfXwvVoM"},
	    {"name": "temple", "location": "https://www.youtube.com/watch?v=YuTE61U3iJM"},
	    {"name": "baal", "location": "https://www.youtube.com/watch?v=xcuz5IofwKo"},
	 ],

	"map":	{
	    "login": "intro",
	    "Lioneye's Watch": "rogue_encampment",
	    "The Twilight Strand": "wild",
	    "The Coast": "wild",
	    "The Tidal Island": "wild",
	    "The Mud Flats": "wild",
	    "The Fetid Pool": "caves",
	    "The Flooded Depths": "caves",
	    "The Submerged Passage": "caves",
	    "The Ledge": "wild",
	    "The Climb": "wild",
	    "The Lower Prison": "monastery",
	    "The Upper Prison": "monastery",
	    "Prisoner's Gate": "wild",
	    "The Ship Graveyard": "tristram",
	    "The Ship Graveyard Cave": "tristram",
	    "The Cavern of Wrath": "crypt",
	    "The Cavern of Anger": "crypt",
	    "The Forest Encampment": "kurast_docks",
	    "The Southern Forest": "jungle",
	    "The Old Fields": "jungle",
	    "The Den": "spider",
	    "The Crossroads": "jungle",
	    "The Crypt Level 1": "kurast_sewers",
	    "The Crypt Level 2": "kurast_sewers",
	    "The Chamber of Sins Level 1": "kurast_sewers",
	    "The Chamber of Sins Level 2": "kurast_sewers",
	    "The Broken Bridge": "kurast",
	    "The Riverways": "jungle",
	    "The Northern Forest": "jungle",
	    "The Western Forest": "jungle",
	    "The Weaver's Chambers": "spider",
	    "The Vaal Ruins": "kurast_sewers",
	    "The Wetlands": "jungle",
	    "The Dread Thicket": "jungle",
	    "The Caverns": "kurast_sewers",
	    "The Ancient Pyramid": "kurast_sewers",
	    "The Fellshrine Ruins": "kurast",
	    "The Sarn Encampment": "lut_gholein",
	    "The City of Sarn": "desert",
	    "The Slums": "desert",
	    "The Crematorium": "tombs",
	    "The Marketplace": "desert",
	    "The Catacombs": "tombs",
	    "The Battlefront": "valley",
	    "The Solaris Temple Level 1": "harem",
	    "The Solaris Temple Level 2": "harem",
	    "The Docks": "valley",
	    "The Sewers": "random",
	    "The Ebony Barracks": "valley",
	    "The Lunaris Temple Level 1": "harem",
	    "The Lunaris Temple Level 2": "harem",
	    "The Imperial Gardens": "valley",
	    "The Library": "sanctuary",
	    "The Archives": "sanctuary",
	    "The Sceptre of God": "tombs",
	    "The Upper Sceptre of God": "tombs",
	    "Highgate": "pandemonium_fortress",
	    "The Aqueduct": "mesa",
	    "The Dried Lake": "mesa",
	    "The Mines Level 1": "lair",
	    "The Mines Level 2": "lair",
	    "The Crystal Veins": "lair",
	    "Kaom's Dream": "mesa",
	    "Kaom's Stronghold": "mesa",
	    "Daresso's Dream": "mesa",
	    "The Grand Arena": "mesa",
	    "The Belly of the Beast Level 1": "diablo",
	    "The Belly of the Beast Level 2": "diablo",
	    "The Harvest": "diablo",
	    "The Ascent": "intro",
	    "The Slave Pens": "siege",
	    "Overseer's Tower": "harrogath",
	    "The Control Blocks": "siege",
	    "Oriath Square": "siege",
	    "The Ruined Square": "siege",
	    "The Templar Courts": "temple",
	    "The Torched Courts": "temple",
	    "The Chamber of Innocence": "baal",
	    "The Ossuary": "ice_caves",
	    "The Reliquary": "ice_caves",
	    "The Cathedral Rooftop": "baal",
	    "The Karui Fortress": "tristram",
	    "The Ridge": "wild",
	    "Shavronne's Tower": "monastery",
	    "The Beacon": "tristram",
	    "The Brine King's Reef": "crypt",
	    "The Bridge Encampment": "kurast_docks",
	    "The Crypt": "kurast_sewers",
	    "Maligaro's Sanctum": "harem",
	    "The Ashen Fields": "jungle",
	    "The Causeway": "kurast",
	    "The Vaal City": "kurast_sewers",
	    "The Temple of Decay Level 1": "spider",
	    "The Temple of Decay Level 2": "spider",
	    "The Sarn Ramparts": "desert",
	    "The Toxic Conduits": "sewer",
	    "Doedre's Cesspool": "sewer",
	    "The Grand Promenade": "valley",
	    "The High Gardens": "sanctuary",
	    "The Bath House": "harem",
	    "The Lunaris Concourse": "tombs",
	    "The Quay": "valley",
	    "The Grain Gate": "valley",
	    "The Imperial Fields": "desert",
	    "The Solaris Concourse": "tombs",
	    "The Harbour Bridge": "sanctuary",
	    "The Blood Aqueduct": "mesa",
	    "The Descent": "intro",
	    "The Vastiri Desert": "desert",
	    "The Oasis": "desert",
	    "The Foothills": "siege",
	    "The Boiling Lake": "wild",
	    "The Tunnel": "lair",
	    "The Quarry": "mesa",
	    "The Refinery": "lair",
	    "The Belly of the Beast": "diablo",
	    "The Rotting Core": "diablo",
	    "Oriath Docks": "harrogath",
	    "The Ravaged Square": "siege",
	    "The Desecrated Chambers": "siege",
	    "The Canals": "baal",
	    "The Feeding Trough": "baal",
	    "Oriath": "options",
	    "The Templar Laboratory": "options",
	    "The Pale Court": "random",
	    "The Apex of Sacrifice": "harem",
	    "The Alluring Abyss": "harem",
	    "Uul-Netol's Domain": "random",
	    "Chayula's Domain": "random",
	    "Xoph's Domain": "random",
	    "Tul's Domain": "random",
	    "Esh's Domain": "random",
	    "Lookout": "random",
	    "Beach": "random",
	    "Graveyard": "tristram",
	    "Dungeon": "monastery",
	    "Alleyways": "random",
	    "Pen": "random",
	    "Desert": "mesa",
	    "Arid Lake": "wild",
	    "Flooded Mine": "random",
	    "Marshes": "random",
	    "Iceberg": "random",
	    "Cage": "random",
	    "Springs": "wild",
	    "Excavation": "valley",
	    "Leyline": "random",
	    "Peninsula": "random",
	    "Port": "random",
	    "Burial Chambers": "random",
	    "Cells": "tombs",
	    "Arcade": "desert",
	    "City Square": "random",
	    "Relic Chambers": "random",
	    "Courthouse": "random",
	    "Strand": "wild",
	    "Whakawairua Tuahu": "wild",
	    "Chateau": "tristram",
	    "Perandus Manor": "tristram",
	    "Grotto": "caves",
	    "Gorge": "wild",
	    "Volcano": "mesa",
	    "Lighthouse": "random",
	    "Canyon": "wild",
	    "Conservatory": "kurast_sewers",
	    "Sulphur Vents": "random",
	    "Haunted Mansion": "crypt",
	    "Maze": "random",
	    "Channel": "mesa",
	    "Toxic Sewer": "random",
	    "Ancient City": "random",
	    "Ivory Temple": "random",
	    "Spider Lair": "spider",
	    "Barrows": "random",
	    "Mausoleum": "random",
	    "Fields": "random",
	    "Jungle Valley": "kurast",
	    "Phantasmagoria": "diablo",
	    "Academy": "sanctuary",
	    "Thicket": "jungle",
	    "Wharf": "valley",
	    "Ashen Wood": "random",
	    "Atoll": "random",
	    "MaelstrÃ¶m of Chaos": "wild",
	    "Cemetery": "kurast",
	    "Hallowed Ground": "random",
	    "Underground Sea": "caves",
	    "Tribunal": "random",
	    "Coral Ruins": "random",
	    "Lava Chamber": "random",
	    "Residence": "tombs",
	    "Ramparts": "random",
	    "Dunes": "jungle",
	    "Pillars of Arun": "random",
	    "Bone Crypt": "random",
	    "Olmec's Sanctum": "tombs",
	    "Underground River": "crypt",
	    "Caer Blaidd, Wolfpack's Den": "random",
	    "Gardens": "random",
	    "Arachnid Nest": "spider",
	    "Bazaar": "desert",
	    "Laboratory": "random",
	    "Infested Valley": "random",
	    "Overgrown Ruin": "kurast_sewers",
	    "Vaal Pyramid": "kurast_sewers",
	    "Vaults of Atziri": "kurast_sewers",
	    "Geode": "random",
	    "Armoury": "random",
	    "Courtyard": "valley",
	    "The Vinktar Square": "valley",
	    "Mud Geyser": "wild",
	    "Shore": "jungle",
	    "Mao Kun": "jungle",
	    "Tropical Island": "jungle",
	    "Mineral Pools": "random",
	    "Moon Temple": "random",
	    "The Twilight Temple": "random",
	    "Sepulchre": "random",
	    "Tower": "random",
	    "Waste Pool": "sewer",
	    "Plateau": "wild",
	    "Estuary": "random",
	    "Vault": "random",
	    "Temple": "harem",
	    "Poorjoy's Asylum": "harem",
	    "Arena": "mesa",
	    "Museum": "sanctuary",
	    "The Putrid Cloister": "random",
	    "Scriptorium": "random",
	    "Siege": "random",
	    "Shipyard": "valley",
	    "Belfry": "random",
	    "Arachnid Tomb": "random",
	    "Wasteland": "mesa",
	    "Precinct": "desert",
	    "Bog": "wild",
	    "Pier": "valley",
	    "Cursed Crypt": "random",
	    "The Coward's Trial": "crypt",
	    "Orchard": "valley",
	    "Promenade": "valley",
	    "The Hall of Grandmasters": "valley",
	    "Lair": "random",
	    "Colonnade": "valley",
	    "Primordial Pool": "random",
	    "Spider Forest": "wild",
	    "Coves": "kurast",
	    "Waterways": "mesa",
	    "Factory": "random",
	    "Mesa": "random",
	    "Pit": "mesa",
	    "Defiled Cathedral": "random",
	    "Summit": "random",
	    "Overgrown Shrine": "kurast_sewers",
	    "Acton's Nightmare": "kurast_sewers",
	    "Castle Ruins": "random",
	    "Crystal Ore": "random",
	    "Villa": "tombs",
	    "Torture Chamber": "monastery",
	    "Oba's Cursed Trove": "monastery",
	    "Necropolis": "monastery",
	    "Death and Taxes": "monastery",
	    "Racecourse": "random",
	    "Caldera": "random",
	    "Ghetto": "desert",
	    "Park": "random",
	    "Malformation": "diablo",
	    "Terrace": "valley",
	    "Shrine": "harem",
	    "Arsenal": "desert",
	    "Desert Spring": "random",
	    "Core": "diablo",
	    "Colosseum": "mesa",
	    "Acid Lakes": "random",
	    "Dark Forest": "jungle",
	    "Crimson Temple": "random",
	    "Plaza": "tristram",
	    "Dig": "random",
	    "Palace": "tombs",
	    "Lava Lake": "random",
	    "Basilica": "random",
	    "Sunken City": "random",
	    "Reef": "jungle",
	    "Carcass": "random",
	    "Pit of the Chimera": "random",
	    "Lair of the Hydra": "random",
	    "Forge of the Phoenix": "random",
	    "Maze of the Minotaur": "random",
	    "The Shaper's Realm": "random",
	    "Vaal Temple": "kurast_sewers",
	    "The Beachhead": "random",
	    "The Warehouse District": "desert",
	    "The Slums Sewers": "sewer",
	    "The Warehouse Sewers": "sewer",
	    "The Market Sewers": "sewer",
	    "The Hedge Maze": "valley",
	    "Kaom's Path": "mesa",
	    "Strange Sinkhole": "diablo",
	    "Concealed Cavity": "diablo",
	    "Sunken Shingle": "diablo",
	    "Clouded Ridge": "diablo",
	    "Forgotten Oubliette": "diablo",
	    "Remote Gulch": "diablo",
	    "Narrow Ravine": "diablo",
	    "Mystical Clearing": "diablo",
	    "Covered-up Hollow": "diablo",
	    "Hidden Patch": "diablo",
	    "Entombed Alcove": "diablo",
	    "Secret Laboratory": "diablo",
	    "Secluded Copse": "diablo",
	    "Forbidden Chamber": "diablo",
	    "Quarantined Quarters": "diablo",
	    "Disused Furnace": "diablo",
	    "Blind Alley": "diablo",
	    "Entombed Chamber": "diablo",
	    "Sacred Chambers": "diablo",
	    "Stagnant Canal": "diablo",
	    "Walled-off Ducts": "diablo",
	    "Neglected Cellar": "diablo",
	    "Arcane Chambers": "diablo",
	    "Inner Grounds": "diablo",
	    "Sealed Corridors": "diablo",
	    "Restricted Gallery": "diablo",
	    "Forgotten Conduit": "diablo",
	    "Ancient Catacomb": "diablo",
	    "Haunted Mineshaft": "diablo",
	    "Abandoned Dam": "diablo",
	    "Haunted Depth": "crypt",
	    "Haunted Abyss": "crypt",
	    "Haunted Descent": "crypt",
	    "Haunted Ruin": "crypt",
	    "Haunted Crypt": "crypt",
	    "Haunted Cave": "crypt",
	    "Haunted Tomb": "crypt",
	    "Haunted Lair": "crypt",
	    "Haunted Catacomb": "crypt",
	    "Haunted Dungeon": "crypt",
	    "Haunted Study": "crypt",
	    "Haunted Trench": "crypt",
	    "Haunted Temple": "crypt",
	    "Haunted Shrine": "crypt",
	    "Haunted Shed": "crypt",
	    "Haunted Cell": "crypt",
	    "Watery Pit": "crypt",
	    "Ruined Arena": "crypt",
	    "Austere Arena": "crypt",
	    "Rugged Pit": "crypt",
	    "Ageless Arena": "crypt",
	    "Webbed Arena": "crypt",
	    "Hallowed Arena": "crypt",
	    "Burnt Cage": "crypt",
	    "Scholars' Arena": "crypt",
	    "Court Arena": "crypt",
	    "Sewage Pit": "crypt",
	    "Polished Arena": "crypt",
	    "Blood Pit": "crypt",
	    "Ramshackle Arena": "crypt",
	    "Decrepit Arena": "crypt",
	    "Sacred Tomb": "crypt",
	    "Spiritual Ruins": "crypt",
	    "Divine Cathedral": "crypt",
	    "Sacred Shrine": "crypt",
	    "Hallowed Shrine": "crypt",
	    "Sanctified Cathedral": "crypt",
	    "Gallery of Wisdom": "crypt",
	    "Solemn Halls": "crypt",
	    "Solitary Chamber": "crypt",
	    "Watery Cave": "crypt",
	    "Watery Tunnels": "crypt",
	    "Ancient Church": "crypt",
	    "Dark Necropolis": "crypt",
	    "Black Forest": "crypt",
	    "Dry Forest": "crypt",
	    "Dry Fields": "crypt",
	    "Lush Forest": "crypt",
	    "Overgrown Garden": "crypt",
	    "Church Ruins": "crypt",
	    "Ancient Ruins": "crypt",
	    "Industrial Docks": "crypt",
	    "Abandoned Jail": "crypt",
	    "Windswept Ridge": "crypt",
	    "Secret Library": "crypt",
	    "Hidden Repository": "crypt",
	    "Experimental Chambers": "crypt",
	    "Market Ruins": "crypt",
	    "Verdant Streams": "crypt",
	    "Abandoned Prison": "crypt",
	    "Ruined Temple": "crypt",
	    "Ruined Palace": "crypt",
	    "Stagnant Sewers": "crypt",
	    "Shipwreck Sanctum": "crypt",
	    "Slum Ruins": "crypt",
	    "Untouched Temple": "crypt",
	    "Spider Woods": "crypt",
	    "Spider Grove": "crypt",
	    "Fetid Swamp": "crypt",
	    "Sand Terraces": "crypt",
	    "Dense Thicket": "crypt",
	    "Abandoned Warehouses": "crypt",
	    "Waterfall Cavern": "crypt",
	    "Desert Valley": "crypt",
	    "Forgotten Cove": "crypt",
	    "Forgotten Wood": "crypt",
	    "Forgotten Slum": "crypt",
	    "Crumbled Laboratory": "crypt",
	    "Dank Den": "caves",
	    "Rotting Den": "caves",
	    "Defiled Den": "caves",
	    "Reeking Den": "caves",
	    "Ancient Den": "caves",
	    "Infested Lair": "caves",
	    "Desecrated Lair": "caves",
	    "Sooty Lair": "caves",
	    "Musty Lair": "caves",
	    "Ruined Lair": "caves",
	    "Rancid Lair": "caves",
	    "Fresh Lair": "caves",
	    "Suffocating Lair": "caves",
	    "Musky Lair": "caves",
	    "Putrid Lair": "caves",
	    "Lair of the Wolven King": "caves",
	    "Aspirants' Plaza": "harem",
	    "Sepulchre Annex": "harem",
	    "Sepulchre Passage": "harem",
	    "Sepulchre Halls": "harem",
	    "Sepulchre Atrium": "harem",
	    "Sanitorium Annex": "harem",
	    "Sanitorium Passage": "harem",
	    "Sanitorium Halls": "harem",
	    "Sanitorium Atrium": "harem",
	    "Mansion Annex": "harem",
	    "Mansion Passage": "harem",
	    "Mansion Halls": "harem",
	    "Mansion Atrium": "harem",
	    "Basilica Annex": "harem",
	    "Basilica Passage": "harem",
	    "Basilica Halls": "harem",
	    "Basilica Atrium": "harem",
	    "Domain Enclosure": "harem",
	    "Domain Path": "harem",
	    "Domain Walkways": "harem",
	    "Domain Crossing": "harem",
	    "Estate Enclosure": "harem",
	    "Estate Path": "harem",
	    "Estate Walkways": "harem",
	    "Estate Crossing": "harem",
	    "Aspirant's Trial": "diablo",
	    "Trial of Crippling Grief": "harem",
	    "Trial of Burning Rage": "harem",
	    "Trial of Swirling Fear": "harem",
	    "Trial of Piercing Truth": "harem",
	    "Trial of Stinging Doubt": "harem",
	    "Trial of Lingering Pain": "harem",
	    "Crypt": "crypt",
	    "Untainted Paradise": "jungle",
	    "Mountain Ledge": "wild",
	    "Sewer": "sewer",
	    "Catacombs": "tombs",
	    "Tunnel": "caves",
	    "Dry Woods": "jungle",
	    "Blackguard Salute": "valley",
	    "Abandoned Cavern": "crypt",
	    "Dry Peninsula": "jungle",
	    "Crematorium": "monastery",
	    "Wraeclast Pantheon": "harem",
	    "Quarry": "valley",
	    "Village Ruin": "jungle",
	    "Abyss": "mesa",
	    "The Chattering Halls": "jungle",
	    "The Croaking Halls": "jungle",
	    "Battle-scarred Hideout": "rogue_encampment",
	    "Coastal Hideout": "lut_gholein",
	    "Lush Hideout": "kurast_docks",
	    "Enlightened Hideout": "rogue_encampment",
	    "Immaculate Hideout": "rogue_encampment",
	    "Bloodsoaked Hideout": "rogue_encampment",
	    "Downtown Hideout": "rogue_encampment",
	    "Lofty Hideout": "rogue_encampment",
	    "Unearthed Hideout": "rogue_encampment",
	    "Backstreet Hideout": "rogue_encampment",
	    "Stockroom Hideout": "rogue_encampment",
	    "Industrial Hideout": "rogue_encampment",
	    "Winding Pier": "lut_gholein",
	    "Sarn Arena": "random",
	    "PvP 1v1 Arena": "random",
	    "PvP 2v2 Arena": "random",
	    "PvP Large Arena": "random",
	    "PvP Blitz Arena": "random",
	    "PvP 1v1 Capture the Flag": "random",
	    "PvP 2v2 Capture the Flag": "random",
	    "PvP 3v3 Capture the Flag": "random",
	    "PvP 6v6 Capture the Flag": "random",
	    "PvP 1v1v1 Capture the Flag": "random",
	    "PvP 2v2v2 Capture the Flag": "random",
	    "PvP 3v3v3 Capture the Flag": "random",
	    "PvP 6v6v6 Capture the Flag": "random",
	    "A Level Under Construction 1 ": "random",
	    "A Level Under Construction 2": "random",
	    "A Level Under Construction 3": "random",
	    "The Eternal Laboratory": "random",
	    "Convent of the Twins' Flame": "random",
	    "PetFlats": "random",
	    "The Phrecia Outskirts": "random",
	    "The Heart of Phrecia": "random",
	    "The Lost Cathedral": "random",
	    "The Mortal Tomb": "random",
	    "The Arachnid Tomb": "random",
	    "The Tomb of Statues": "random",
	    "The Frozen Abyss": "random",
	    "The Simian Cave": "random",
	    "The Skeletal Caverns": "random",
	    "The Forbidden Ruins": "random",
	    "The Vault of the Guardians": "random",
	    "The Hall of Heroes": "random",
	    "The Desecrated Shrine": "random",
	    "The Demonic Shrine": "random",
	    "The Infernal Shrine": "random",
	    "The Entrance Hall": "random",
	    "The Rasping Halls": "random",
	    "The Freezing Chamber": "random",
	    "The Shrine of the Pagan God": "random",
	    "The Dungeon of Anarchy": "random",
	    "The Dungeon of Necromancy": "random",
	    "The Hollow Cave": "random",
	    "The Haunted Dungeon": "random",
	    "The Obelisks of Faith": "random",
	    "The Burning Cave": "random",
	    "The Chamber of Greed": "random",
	    "The Cage": "random",
	    "The Necromantic Crypt": "random",
	    "The Diabolic Crypt": "random",
	    "The Misty Cave": "random",
	    "The Ember Crypt": "random",
	    "The Stormy Ledge": "random",
	    "The Frozen Cave": "random",
	    "The Glittering Crypt": "random",
	    "The Glittering Cave": "random",
	    "The Inner Halls Level 1": "random",
	    "The Inner Halls Level 2": "random",
	    "The Inner Halls Level 3": "random",
	    "The Nexus": "random",
	    "The Endless Ledge": "random",
	    "Baleful Hideout": "random",
	    "Undercity Hideout": "random",
	    "Cavernous Hideout": "random",
	    "Forsaken Hideout": "random",
	    "Overgrown Hideout": "random",
	    "HideoutShip1": "random",
	    "Sarn Arena Staging Area": "random",
	    "Animation Test Area": "random",
	    "Light Test": "random",
	    "Rhoa Fight": "random",
	    "Arrow Test": "random",
		"RoomTest": "random",
		"Azurite Mine": "random"
	}
}  

let worldAreas = {
	"1_1_town": "Lioneye's Watch",
	"1_1_1": "The Twilight Strand",
	"1_1_2_test1": "A Level Under Construction 1 ",
	"1_1_2_test2": "A Level Under Construction 2",
	"1_1_2_test3": "A Level Under Construction 3",
	"1_1_2": "The Coast",
	"1_1_2a": "The Tidal Island",
	"1_1_3": "The Mud Flats",
	"1_1_3a": "The Fetid Pool",
	"1_1_4_0": "The Flooded Depths",
	"1_1_4_1": "The Submerged Passage",
	"1_1_5": "The Ledge",
	"1_1_6": "The Climb",
	"1_1_7_1": "The Lower Prison",
	"1_1_7_2": "The Upper Prison",
	"1_1_8": "Prisoner's Gate",
	"1_1_9": "The Ship Graveyard",
	"1_1_9a": "The Ship Graveyard Cave",
	"1_1_11_1": "The Cavern of Wrath",
	"1_1_11_2": "The Cavern of Anger",
	"1_2_town": "The Forest Encampment",
	"1_2_1": "The Southern Forest",
	"1_2_2": "The Old Fields",
	"1_2_2a": "The Den",
	"1_2_3": "The Crossroads",
	"1_2_5_1": "The Crypt Level 1",
	"1_2_5_2": "The Crypt Level 2",
	"1_2_6_1": "The Chamber of Sins Level 1",
	"1_2_6_3": "The Chamber of Sins Level 2",
	"1_2_4": "The Broken Bridge",
	"1_2_7": "The Riverways",
	"1_2_8": "The Northern Forest",
	"1_2_9": "The Western Forest",
	"1_2_10": "The Weaver's Chambers",
	"1_2_11_1": "The Vaal Ruins",
	"1_2_12": "The Wetlands",
	"1_2_13": "The Dread Thicket",
	"1_2_14_2": "The Caverns",
	"1_2_14_3": "The Ancient Pyramid",
	"1_2_15": "The Fellshrine Ruins",
	"1_3_town": "The Sarn Encampment",
	"1_3_1": "The City of Sarn",
	"1_3_2": "The Slums",
	"1_3_3_1": "The Crematorium",
	"1_3_4": "The Warehouse District",
	"1_3_5": "The Marketplace",
	"1_3_6_1": "The Catacombs",
	"1_3_7": "The Battlefront",
	"1_3_8_1": "The Solaris Temple Level 1",
	"1_3_8_2": "The Solaris Temple Level 2",
	"1_3_9": "The Docks",
	"1_3_10_0": "The Slums Sewers",
	"1_3_10_1": "The Warehouse Sewers",
	"1_3_10_2": "The Market Sewers",
	"1_3_13": "The Ebony Barracks",
	"1_3_14_1": "The Lunaris Temple Level 1",
	"1_3_14_3": "The Lunaris Temple Level 2",
	"1_3_15": "The Imperial Gardens",
	"1_3_16": "The Hedge Maze",
	"1_3_17_1": "The Library",
	"1_3_17_2": "The Archives",
	"1_3_18_1": "The Sceptre of God",
	"1_3_18_2": "The Upper Sceptre of God",
	"1_4_town": "Highgate",
	"1_4_1": "The Aqueduct",
	"1_4_2": "The Dried Lake",
	"1_4_3_1": "The Mines Level 1",
	"1_4_3_2": "The Mines Level 2",
	"1_4_3_3": "The Crystal Veins",
	"1_4_4_1": "Kaom's Dream",
	"1_4_4_2": "Kaom's Path",
	"1_4_4_3": "Kaom's Stronghold",
	"1_4_5_1": "Daresso's Dream",
	"1_4_5_2": "The Grand Arena",
	"1_4_6_1": "The Belly of the Beast Level 1",
	"1_4_6_2": "The Belly of the Beast Level 2",
	"1_4_6_3": "The Harvest",
	"2_1_town": "Lioneye's Watch",
	"2_1_1": "The Twilight Strand",
	"2_1_2": "The Coast",
	"2_1_2a": "The Tidal Island",
	"2_1_3": "The Mud Flats",
	"2_1_3a": "The Fetid Pool",
	"2_1_4_0": "The Flooded Depths",
	"2_1_4_1": "The Submerged Passage",
	"2_1_5": "The Ledge",
	"2_1_6": "The Climb",
	"2_1_7_1": "The Lower Prison",
	"2_1_7_2": "The Upper Prison",
	"2_1_8": "Prisoner's Gate",
	"2_1_9": "The Ship Graveyard",
	"2_1_9a": "The Ship Graveyard Cave",
	"2_1_11_1": "The Cavern of Wrath",
	"2_1_11_2": "The Cavern of Anger",
	"2_2_town": "The Forest Encampment",
	"2_2_1": "The Southern Forest",
	"2_2_2": "The Old Fields",
	"2_2_2a": "The Den",
	"2_2_3": "The Crossroads",
	"2_2_5_1": "The Crypt Level 1",
	"2_2_5_2": "The Crypt Level 2",
	"2_2_6_1": "The Chamber of Sins Level 1",
	"2_2_6_3": "The Chamber of Sins Level 2",
	"2_2_4": "The Broken Bridge",
	"2_2_7": "The Riverways",
	"2_2_8": "The Northern Forest",
	"2_2_9": "The Western Forest",
	"2_2_10": "The Weaver's Chambers",
	"2_2_11_1": "The Vaal Ruins",
	"2_2_12": "The Wetlands",
	"2_2_13": "The Dread Thicket",
	"2_2_14_2": "The Caverns",
	"2_2_14_3": "The Ancient Pyramid",
	"2_2_15": "The Fellshrine Ruins",
	"2_3_town": "The Sarn Encampment",
	"2_3_1": "The City of Sarn",
	"2_3_2": "The Slums",
	"2_3_3_1": "The Crematorium",
	"2_3_4": "The Warehouse District",
	"2_3_5": "The Marketplace",
	"2_3_6_1": "The Catacombs",
	"2_3_7": "The Battlefront",
	"2_3_8_1": "The Solaris Temple Level 1",
	"2_3_8_2": "The Solaris Temple Level 2",
	"2_3_9": "The Docks",
	"2_3_10_0": "The Slums Sewers",
	"2_3_10_1": "The Warehouse Sewers",
	"2_3_10_2": "The Market Sewers",
	"2_3_13": "The Ebony Barracks",
	"2_3_14_1": "The Lunaris Temple Level 1",
	"2_3_14_3": "The Lunaris Temple Level 2",
	"2_3_15": "The Imperial Gardens",
	"2_3_16": "The Hedge Maze",
	"2_3_17_1": "The Library",
	"2_3_17_2": "The Archives",
	"2_3_18_1": "The Sceptre of God",
	"2_3_18_2": "The Upper Sceptre of God",
	"2_4_town": "Highgate",
	"2_4_1": "The Aqueduct",
	"2_4_2": "The Dried Lake",
	"2_4_3_1": "The Mines Level 1",
	"2_4_3_2": "The Mines Level 2",
	"2_4_3_3": "The Crystal Veins",
	"2_4_4_1": "Kaom's Dream",
	"2_4_4_2": "Kaom's Path",
	"2_4_4_3": "Kaom's Stronghold",
	"2_4_5_1": "Daresso's Dream",
	"2_4_5_2": "The Grand Arena",
	"2_4_6_1": "The Belly of the Beast Level 1",
	"2_4_6_2": "The Belly of the Beast Level 2",
	"2_4_6_3": "The Harvest",
	"3_1_town": "Lioneye's Watch",
	"3_1_1": "The Twilight Strand",
	"3_1_2": "The Coast",
	"3_1_2a": "The Tidal Island",
	"3_1_3": "The Mud Flats",
	"3_1_3a": "The Fetid Pool",
	"3_1_4_0": "The Flooded Depths",
	"3_1_4_1": "The Submerged Passage",
	"3_1_5": "The Ledge",
	"3_1_6": "The Climb",
	"3_1_7_1": "The Lower Prison",
	"3_1_7_2": "The Upper Prison",
	"3_1_8": "Prisoner's Gate",
	"3_1_9": "The Ship Graveyard",
	"3_1_9a": "The Ship Graveyard Cave",
	"3_1_11_1": "The Cavern of Wrath",
	"3_1_11_2": "The Cavern of Anger",
	"3_2_town": "The Forest Encampment",
	"3_2_1": "The Southern Forest",
	"3_2_2": "The Old Fields",
	"3_2_2a": "The Den",
	"3_2_3": "The Crossroads",
	"3_2_5_1": "The Crypt Level 1",
	"3_2_5_2": "The Crypt Level 2",
	"3_2_6_1": "The Chamber of Sins Level 1",
	"3_2_6_3": "The Chamber of Sins Level 2",
	"3_2_4": "The Broken Bridge",
	"3_2_7": "The Riverways",
	"3_2_8": "The Northern Forest",
	"3_2_9": "The Western Forest",
	"3_2_10": "The Weaver's Chambers",
	"3_2_11_1": "The Vaal Ruins",
	"3_2_12": "The Wetlands",
	"3_2_13": "The Dread Thicket",
	"3_2_14_2": "The Caverns",
	"3_2_14_3": "The Ancient Pyramid",
	"3_2_15": "The Fellshrine Ruins",
	"3_3_town": "The Sarn Encampment",
	"3_3_1": "The City of Sarn",
	"3_3_2": "The Slums",
	"3_3_3_1": "The Crematorium",
	"3_3_4": "The Warehouse District",
	"3_3_5": "The Marketplace",
	"3_3_6_1": "The Catacombs",
	"3_3_7": "The Battlefront",
	"3_3_8_1": "The Solaris Temple Level 1",
	"3_3_8_2": "The Solaris Temple Level 2",
	"3_3_9": "The Docks",
	"3_3_10_0": "The Slums Sewers",
	"3_3_10_1": "The Warehouse Sewers",
	"3_3_10_2": "The Market Sewers",
	"3_3_13": "The Ebony Barracks",
	"3_3_14_1": "The Lunaris Temple Level 1",
	"3_3_14_3": "The Lunaris Temple Level 2",
	"3_3_15": "The Imperial Gardens",
	"3_3_16": "The Hedge Maze",
	"3_3_17_1": "The Library",
	"3_3_17_2": "The Archives",
	"3_3_18_1": "The Sceptre of God",
	"3_3_18_2": "The Upper Sceptre of God",
	"3_4_town": "Highgate",
	"3_4_1": "The Aqueduct",
	"3_4_2": "The Dried Lake",
	"3_4_3_1": "The Mines Level 1",
	"3_4_3_2": "The Mines Level 2",
	"3_4_3_3": "The Crystal Veins",
	"3_4_4_1": "Kaom's Dream",
	"3_4_4_2": "Kaom's Path",
	"3_4_4_3": "Kaom's Stronghold",
	"3_4_5_1": "Daresso's Dream",
	"3_4_5_2": "The Grand Arena",
	"3_4_6_1": "The Belly of the Beast Level 1",
	"3_4_6_2": "The Belly of the Beast Level 2",
	"3_4_6_3": "The Harvest",
	"3_3_8_4": "The Eternal Laboratory",
	"1_SideArea1_1Intro": "Strange Sinkhole",
	"1_SideArea1_2Intro": "Concealed Cavity",
	"1_SideArea1_1": "Strange Sinkhole",
	"1_SideArea1_2": "Concealed Cavity",
	"1_SideArea1_3": "Sunken Shingle",
	"1_SideArea1_4_": "Clouded Ridge",
	"1_SideArea1_5": "Forgotten Oubliette",
	"1_SideArea1_6": "Remote Gulch",
	"1_SideArea2_1": "Narrow Ravine",
	"1_SideArea2_2": "Mystical Clearing",
	"1_SideArea2_3": "Covered-up Hollow",
	"1_SideArea2_4": "Hidden Patch",
	"1_SideArea2_5": "Entombed Alcove",
	"1_SideArea2_6": "Secret Laboratory",
	"1_SideArea2_7": "Secluded Copse",
	"1_SideArea2_7Intro": "Secluded Copse",
	"1_SideArea2_8": "Forbidden Chamber",
	"1_SideArea3_1": "Quarantined Quarters",
	"1_SideArea3_2": "Disused Furnace",
	"1_SideArea3_3": "Blind Alley",
	"1_SideArea3_4": "Entombed Chamber",
	"1_SideArea3_5": "Sacred Chambers",
	"1_SideArea3_6": "Stagnant Canal",
	"1_SideArea3_7": "Walled-off Ducts",
	"1_SideArea3_8": "Neglected Cellar",
	"1_SideArea3_8Intro": "Neglected Cellar",
	"1_SideArea3_9_": "Arcane Chambers",
	"1_SideArea3_10": "Inner Grounds",
	"1_SideArea3_11": "Sealed Corridors",
	"1_SideArea3_12": "Restricted Gallery",
	"1_SideArea4_1Intro": "Forgotten Conduit",
	"1_SideArea4_1": "Forgotten Conduit",
	"1_SideArea4_2": "Ancient Catacomb",
	"1_SideArea4_3": "Haunted Mineshaft",
	"1_SideArea4_4": "Abandoned Dam",
	"2_SideArea1_1Intro": "Strange Sinkhole",
	"2_SideArea1_2Intro": "Concealed Cavity",
	"2_SideArea1_1": "Strange Sinkhole",
	"2_SideArea1_2": "Concealed Cavity",
	"2_SideArea1_3": "Sunken Shingle",
	"2_SideArea1_4_": "Clouded Ridge",
	"2_SideArea1_5": "Forgotten Oubliette",
	"2_SideArea1_6": "Remote Gulch",
	"2_SideArea2_1": "Narrow Ravine",
	"2_SideArea2_2": "Mystical Clearing",
	"2_SideArea2_3": "Covered-up Hollow",
	"2_SideArea2_4": "Hidden Patch",
	"2_SideArea2_5": "Entombed Alcove",
	"2_SideArea2_6": "Secret Laboratory",
	"2_SideArea2_7": "Secluded Copse",
	"2_SideArea2_7Intro": "Secluded Copse",
	"2_SideArea2_8": "Forbidden Chamber",
	"2_SideArea3_1": "Quarantined Quarters",
	"2_SideArea3_2": "Disused Furnace",
	"2_SideArea3_3": "Blind Alley",
	"2_SideArea3_4": "Entombed Chamber",
	"2_SideArea3_5": "Sacred Chambers",
	"2_SideArea3_6": "Stagnant Canal",
	"2_SideArea3_7": "Walled-off Ducts",
	"2_SideArea3_8": "Neglected Cellar",
	"2_SideArea3_8Intro": "Neglected Cellar",
	"2_SideArea3_9_": "Arcane Chambers",
	"2_SideArea3_10": "Inner Grounds",
	"2_SideArea3_11": "Sealed Corridors",
	"2_SideArea3_12": "Restricted Gallery",
	"2_SideArea4_1Intro": "Forgotten Conduit",
	"2_SideArea4_1": "Forgotten Conduit",
	"2_SideArea4_2": "Ancient Catacomb",
	"2_SideArea4_3": "Haunted Mineshaft",
	"2_SideArea4_4": "Abandoned Dam",
	"3_SideArea1_1": "Strange Sinkhole",
	"3_SideArea1_2": "Concealed Cavity",
	"3_SideArea1_1Intro": "Strange Sinkhole",
	"3_SideArea1_2Intro": "Concealed Cavity",
	"3_SideArea1_3": "Sunken Shingle",
	"3_SideArea1_4_": "Clouded Ridge",
	"3_SideArea1_5": "Forgotten Oubliette",
	"3_SideArea1_6": "Remote Gulch",
	"3_SideArea2_1": "Narrow Ravine",
	"3_SideArea2_2": "Mystical Clearing",
	"3_SideArea2_3": "Covered-up Hollow",
	"3_SideArea2_4": "Hidden Patch",
	"3_SideArea2_5": "Entombed Alcove",
	"3_SideArea2_6": "Secret Laboratory",
	"3_SideArea2_7": "Secluded Copse",
	"3_SideArea2_7Intro": "Secluded Copse",
	"3_SideArea2_8": "Forbidden Chamber",
	"3_SideArea3_1": "Quarantined Quarters",
	"3_SideArea3_2": "Disused Furnace",
	"3_SideArea3_3": "Blind Alley",
	"3_SideArea3_4": "Entombed Chamber",
	"3_SideArea3_5": "Sacred Chambers",
	"3_SideArea3_6": "Stagnant Canal",
	"3_SideArea3_7": "Walled-off Ducts",
	"3_SideArea3_8": "Neglected Cellar",
	"3_SideArea3_8Intro": "Neglected Cellar",
	"3_SideArea3_9_": "Arcane Chambers",
	"3_SideArea3_10": "Inner Grounds",
	"3_SideArea3_11": "Sealed Corridors",
	"3_SideArea3_12": "Restricted Gallery",
	"3_SideArea4_1Intro": "Forgotten Conduit",
	"3_SideArea4_1": "Forgotten Conduit",
	"3_SideArea4_2": "Ancient Catacomb",
	"3_SideArea4_3": "Haunted Mineshaft",
	"3_SideArea4_4": "Abandoned Dam",
	"1_Mission1_1": "Haunted Depth",
	"1_Mission1_2": "Haunted Abyss",
	"1_Mission1_3": "Haunted Descent",
	"1_Mission1_4": "Haunted Ruin",
	"1_Mission1_5": "Haunted Crypt",
	"1_Mission1_6": "Haunted Cave",
	"1_Mission1_7": "Haunted Tomb",
	"1_Mission1_8": "Haunted Lair",
	"1_Mission1_9": "Haunted Catacomb",
	"1_Mission1_10": "Haunted Dungeon",
	"1_Mission1_11": "Haunted Study",
	"1_Mission1_12": "Haunted Mansion",
	"1_Mission1_13": "Haunted Trench",
	"1_Mission1_14": "Haunted Temple",
	"1_Mission1_15": "Haunted Shrine",
	"1_Mission1_16": "Haunted Shed",
	"1_Mission1_17": "Haunted Cell",
	"2_Mission1_1": "Haunted Depth",
	"2_Mission1_2": "Haunted Abyss",
	"2_Mission1_3": "Haunted Descent",
	"2_Mission1_4": "Haunted Ruin",
	"2_Mission1_5": "Haunted Crypt",
	"2_Mission1_6": "Haunted Cave",
	"2_Mission1_7": "Haunted Tomb",
	"2_Mission1_8": "Haunted Lair",
	"2_Mission1_9": "Haunted Catacomb",
	"2_Mission1_10": "Haunted Dungeon",
	"2_Mission1_11": "Haunted Study",
	"2_Mission1_12": "Haunted Mansion",
	"2_Mission1_13": "Haunted Trench",
	"2_Mission1_14": "Haunted Temple",
	"2_Mission1_15": "Haunted Shrine",
	"2_Mission1_16": "Haunted Shed",
	"2_Mission1_17": "Haunted Cell",
	"3_Mission1_1": "Haunted Depth",
	"3_Mission1_2": "Haunted Abyss",
	"3_Mission1_3": "Haunted Descent",
	"3_Mission1_4": "Haunted Ruin",
	"3_Mission1_5": "Haunted Crypt",
	"3_Mission1_6": "Haunted Cave",
	"3_Mission1_7": "Haunted Tomb",
	"3_Mission1_8": "Haunted Lair",
	"3_Mission1_9": "Haunted Catacomb",
	"3_Mission1_10": "Haunted Dungeon",
	"3_Mission1_11": "Haunted Study",
	"3_Mission1_12": "Haunted Mansion",
	"3_Mission1_13": "Haunted Trench",
	"3_Mission1_14": "Haunted Temple",
	"3_Mission1_15": "Haunted Shrine",
	"3_Mission1_16": "Haunted Shed",
	"3_Mission1_17": "Haunted Cell",
	"1_Den1": "Dank Den",
	"1_Den2": "Rotting Den",
	"1_Den3": "Defiled Den",
	"1_Den4": "Reeking Den",
	"1_Den5": "Ancient Den",
	"1_Den6": "Infested Lair",
	"1_Den7": "Desecrated Lair",
	"1_Den8": "Sooty Lair",
	"1_Den9": "Musty Lair",
	"1_Den10": "Ruined Lair",
	"1_Den11": "Rancid Lair",
	"1_Den12": "Fresh Lair",
	"1_Den13": "Suffocating Lair",
	"1_Den14": "Musky Lair",
	"1_Den15": "Putrid Lair",
	"2_Den1": "Dank Den",
	"2_Den2": "Rotting Den",
	"2_Den3": "Defiled Den",
	"2_Den4": "Reeking Den",
	"2_Den5": "Ancient Den",
	"2_Den6": "Infested Lair",
	"2_Den7": "Desecrated Lair",
	"2_Den8": "Sooty Lair",
	"2_Den9": "Musty Lair",
	"2_Den10": "Ruined Lair",
	"2_Den11": "Rancid Lair",
	"2_Den12": "Fresh Lair",
	"2_Den13": "Suffocating Lair",
	"2_Den14": "Musky Lair",
	"2_Den15": "Putrid Lair",
	"3_Den1": "Dank Den",
	"3_Den2": "Rotting Den",
	"3_Den3": "Defiled Den",
	"3_Den4": "Reeking Den",
	"3_Den5": "Ancient Den",
	"3_Den6_": "Infested Lair",
	"3_Den7": "Desecrated Lair",
	"3_Den8": "Sooty Lair",
	"3_Den9": "Musty Lair",
	"3_Den10": "Ruined Lair",
	"3_Den11": "Rancid Lair",
	"3_Den12": "Fresh Lair",
	"3_Den13": "Suffocating Lair",
	"3_Den14": "Musky Lair",
	"3_Den15": "Putrid Lair",
	"1_Arena1": "Watery Pit",
	"1_Arena2": "Ruined Arena",
	"1_Arena3": "Austere Arena",
	"1_Arena4": "Rugged Pit",
	"1_Arena5": "Ageless Arena",
	"1_Arena6": "Webbed Arena",
	"1_Arena7": "Hallowed Arena",
	"1_Arena8": "Burnt Cage",
	"1_Arena9": "Scholars' Arena",
	"1_Arena10": "Court Arena",
	"1_Arena11": "Sewage Pit",
	"1_Arena12": "Polished Arena",
	"1_Arena13": "Blood Pit",
	"1_Arena14": "Ramshackle Arena",
	"1_Arena15": "Decrepit Arena",
	"2_Arena1": "Watery Pit",
	"2_Arena2": "Ruined Arena",
	"2_Arena3": "Austere Arena",
	"2_Arena4": "Rugged Pit",
	"2_Arena5": "Ageless Arena",
	"2_Arena6": "Webbed Arena",
	"2_Arena7": "Hallowed Arena",
	"2_Arena8": "Burnt Cage",
	"2_Arena9": "Scholars' Arena",
	"2_Arena10": "Court Arena",
	"2_Arena11": "Sewage Pit",
	"2_Arena12": "Polished Arena",
	"2_Arena13": "Blood Pit",
	"2_Arena14": "Ramshackle Arena",
	"2_Arena15": "Decrepit Arena",
	"3_Arena1": "Watery Pit",
	"3_Arena2": "Ruined Arena",
	"3_Arena3": "Austere Arena",
	"3_Arena4": "Rugged Pit",
	"3_Arena5": "Ageless Arena",
	"3_Arena6": "Webbed Arena",
	"3_Arena7": "Hallowed Arena",
	"3_Arena8": "Burnt Cage",
	"3_Arena9": "Scholars' Arena",
	"3_Arena10": "Court Arena",
	"3_Arena11": "Sewage Pit",
	"3_Arena12": "Polished Arena",
	"3_Arena13": "Blood Pit",
	"3_Arena14": "Ramshackle Arena",
	"3_Arena15": "Decrepit Arena",
	"1_Relic1": "Sacred Tomb",
	"1_Relic2": "Spiritual Ruins",
	"1_Relic3": "Divine Cathedral",
	"1_Relic4": "Sacred Shrine",
	"1_Relic5": "Hallowed Shrine",
	"1_Relic6": "Sanctified Cathedral",
	"1_Relic7": "Gallery of Wisdom",
	"1_Relic8": "Solemn Halls",
	"1_Relic9": "Solitary Chamber",
	"2_Relic1": "Sacred Tomb",
	"2_Relic2": "Spiritual Ruins",
	"2_Relic3": "Divine Cathedral",
	"2_Relic4": "Sacred Shrine",
	"2_Relic5": "Hallowed Shrine",
	"2_Relic6": "Sanctified Cathedral",
	"2_Relic7": "Gallery of Wisdom",
	"2_Relic8": "Solemn Halls",
	"2_Relic9": "Solitary Chamber",
	"3_Relic1": "Sacred Tomb",
	"3_Relic2": "Spiritual Ruins",
	"3_Relic3": "Divine Cathedral",
	"3_Relic4": "Sacred Shrine",
	"3_Relic5": "Hallowed Shrine",
	"3_Relic6": "Sanctified Cathedral",
	"3_Relic7": "Gallery of Wisdom",
	"3_Relic8": "Solemn Halls",
	"3_Relic9": "Solitary Chamber",
	"1_Daily1": "Watery Cave",
	"1_Daily2": "Watery Tunnels",
	"1_Daily3": "Ancient Church",
	"1_Daily4": "Dark Necropolis",
	"1_Daily5": "Black Forest",
	"1_Daily6": "Dry Forest",
	"1_Daily7": "Dry Fields",
	"1_Daily8": "Lush Forest",
	"1_Daily9": "Overgrown Garden",
	"1_Daily10": "Church Ruins",
	"1_Daily11": "Ancient Ruins",
	"1_Daily12": "Industrial Docks",
	"1_Daily13": "Abandoned Jail",
	"1_Daily14": "Windswept Ridge",
	"1_Daily15": "Secret Library",
	"1_Daily16": "Hidden Repository",
	"1_Daily17": "Experimental Chambers",
	"1_Daily18": "Market Ruins",
	"1_Daily19": "Verdant Streams",
	"1_Daily20": "Abandoned Prison",
	"1_Daily21": "Ruined Temple",
	"1_Daily22": "Ruined Palace",
	"1_Daily23": "Stagnant Sewers",
	"1_Daily24": "Shipwreck Sanctum",
	"1_Daily25": "Slum Ruins",
	"1_Daily26": "Untouched Temple",
	"1_Daily27": "Spider Woods",
	"1_Daily28": "Spider Grove",
	"1_Daily29": "Fetid Swamp",
	"1_Daily30": "Sand Terraces",
	"1_Daily31": "Dense Thicket",
	"1_Daily32": "Abandoned Warehouses",
	"1_Daily33": "Waterfall Cavern",
	"1_Daily34": "Desert Valley",
	"2_Daily1": "Watery Cave",
	"2_Daily2": "Watery Tunnels",
	"2_Daily3": "Ancient Church",
	"2_Daily4": "Dark Necropolis",
	"2_Daily5": "Black Forest",
	"2_Daily6": "Dry Forest",
	"2_Daily7": "Dry Fields",
	"2_Daily8": "Lush Forest",
	"2_Daily9": "Overgrown Garden",
	"2_Daily10": "Church Ruins",
	"2_Daily11": "Ancient Ruins",
	"2_Daily12": "Industrial Docks",
	"2_Daily13": "Abandoned Jail",
	"2_Daily14": "Windswept Ridge",
	"2_Daily15_": "Secret Library",
	"2_Daily16": "Hidden Repository",
	"2_Daily17": "Experimental Chambers",
	"2_Daily18": "Market Ruins",
	"2_Daily19": "Verdant Streams",
	"2_Daily20": "Abandoned Prison",
	"2_Daily21": "Ruined Temple",
	"2_Daily22": "Ruined Palace",
	"2_Daily23": "Stagnant Sewers",
	"2_Daily24": "Shipwreck Sanctum",
	"2_Daily25": "Slum Ruins",
	"2_Daily26": "Untouched Temple",
	"2_Daily27": "Spider Woods",
	"2_Daily28": "Spider Grove",
	"2_Daily29": "Fetid Swamp",
	"2_Daily30": "Sand Terraces",
	"2_Daily31": "Dense Thicket",
	"2_Daily32": "Abandoned Warehouses",
	"2_Daily33": "Waterfall Cavern",
	"2_Daily34": "Desert Valley",
	"3_Daily1": "Watery Cave",
	"3_Daily2": "Watery Tunnels",
	"3_Daily3": "Ancient Church",
	"3_Daily4": "Dark Necropolis",
	"3_Daily5": "Black Forest",
	"3_Daily6": "Dry Forest",
	"3_Daily7": "Dry Fields",
	"3_Daily8": "Lush Forest",
	"3_Daily9": "Overgrown Garden",
	"3_Daily10": "Church Ruins",
	"3_Daily11": "Ancient Ruins",
	"3_Daily12": "Industrial Docks",
	"3_Daily13": "Abandoned Jail",
	"3_Daily14": "Windswept Ridge",
	"3_Daily15": "Secret Library",
	"3_Daily16": "Hidden Repository",
	"3_Daily17": "Experimental Chambers",
	"3_Daily18": "Market Ruins",
	"3_Daily19": "Verdant Streams",
	"3_Daily20": "Abandoned Prison",
	"3_Daily21": "Ruined Temple",
	"3_Daily22": "Ruined Palace",
	"3_Daily23": "Stagnant Sewers",
	"3_Daily24": "Shipwreck Sanctum",
	"3_Daily25": "Slum Ruins",
	"3_Daily26": "Untouched Temple",
	"3_Daily27": "Spider Woods",
	"3_Daily28": "Spider Grove",
	"3_Daily29": "Fetid Swamp",
	"3_Daily30": "Sand Terraces",
	"3_Daily31": "Dense Thicket",
	"3_Daily32": "Abandoned Warehouses",
	"3_Daily33": "Waterfall Cavern",
	"3_Daily34": "Desert Valley",
	"1_Daily2_1": "Forgotten Cove",
	"1_Daily2_2": "Forgotten Wood",
	"1_Daily2_3": "Forgotten Slum",
	"2_Daily2_1": "Forgotten Cove",
	"2_Daily2_2": "Forgotten Wood",
	"2_Daily2_3": "Forgotten Slum",
	"3_Daily2_1": "Forgotten Cove",
	"3_Daily2_2": "Forgotten Wood",
	"3_Daily2_3": "Forgotten Slum",
	"1_Daily3_1": "Crumbled Laboratory",
	"2_Daily3_1": "Crumbled Laboratory",
	"3_Daily3_1": "Crumbled Laboratory",
	"3_TalismanBoss": "Lair of the Wolven King",
	"3_ProphecyBoss": "The Pale Court",
	"1_Labyrinth_Airlock": "Aspirants' Plaza",
	"2_Labyrinth_Airlock": "Aspirants' Plaza",
	"3_Labyrinth_Airlock": "Aspirants' Plaza",
	"EndGame_Labyrinth_Airlock_#": "Aspirants' Plaza",
	"1_Labyrinth_AirlockClean": "Aspirants' Plaza",
	"1_Labyrinth_C_end": "Sepulchre Annex",
	"1_Labyrinth_C_end_bottleneck": "Sepulchre Annex",
	"1_Labyrinth_C_straight": "Sepulchre Passage",
	"1_Labyrinth_C_straight_bottleneck": "Sepulchre Passage",
	"1_Labyrinth_C_branch": "Sepulchre Halls",
	"1_Labyrinth_C_branch_bottleneck_1": "Sepulchre Halls",
	"1_Labyrinth_C_branch_bottleneck_2": "Sepulchre Halls",
	"1_Labyrinth_C_branch_door": "Sepulchre Halls",
	"1_Labyrinth_C_quad": "Sepulchre Atrium",
	"1_Labyrinth_C_quad_bottleneck": "Sepulchre Atrium",
	"1_Labyrinth_C_quad_door": "Sepulchre Atrium",
	"1_Labyrinth_P_end": "Sanitorium Annex",
	"1_Labyrinth_P_end_bottleneck": "Sanitorium Annex",
	"1_Labyrinth_P_straight": "Sanitorium Passage",
	"1_Labyrinth_P_straight_bottleneck": "Sanitorium Passage",
	"1_Labyrinth_P_branch": "Sanitorium Halls",
	"1_Labyrinth_P_branch_bottleneck_1": "Sanitorium Halls",
	"1_Labyrinth_P_branch_bottleneck_2": "Sanitorium Halls",
	"1_Labyrinth_P_branch_door": "Sanitorium Halls",
	"1_Labyrinth_P_quad": "Sanitorium Atrium",
	"1_Labyrinth_P_quad_bottleneck": "Sanitorium Atrium",
	"1_Labyrinth_P_quad_door": "Sanitorium Atrium",
	"1_Labyrinth_EH_end": "Mansion Annex",
	"1_Labyrinth_EH_end_bottleneck": "Mansion Annex",
	"1_Labyrinth_EH_straight_#": "Mansion Passage",
	"1_Labyrinth_EH_straight_bottleneck": "Mansion Passage",
	"1_Labyrinth_EH_branch": "Mansion Halls",
	"1_Labyrinth_EH_branch_bottleneck_1": "Mansion Halls",
	"1_Labyrinth_EH_branch_bottleneck_2": "Mansion Halls",
	"1_Labyrinth_EH_branch_door": "Mansion Halls",
	"1_Labyrinth_EH_quad": "Mansion Atrium",
	"1_Labyrinth_EH_quad_bottleneck": "Mansion Atrium",
	"1_Labyrinth_EH_quad_door_#": "Mansion Atrium",
	"1_Labyrinth_RT_end": "Basilica Annex",
	"1_Labyrinth_RT_end_bottleneck": "Basilica Annex",
	"1_Labyrinth_RT_straight": "Basilica Passage",
	"1_Labyrinth_RT_straight_bottleneck": "Basilica Passage",
	"1_Labyrinth_RT_branch": "Basilica Halls",
	"1_Labyrinth_RT_branch_bottleneck_1": "Basilica Halls",
	"1_Labyrinth_RT_branch_bottleneck_2": "Basilica Halls",
	"1_Labyrinth_RT_branch_door": "Basilica Halls",
	"1_Labyrinth_RT_quad_#": "Basilica Atrium",
	"1_Labyrinth_RT_quad_bottleneck": "Basilica Atrium",
	"1_Labyrinth_RT_quad_door": "Basilica Atrium",
	"1_Labyrinth_DG_end": "Domain Enclosure",
	"1_Labyrinth_DG_end_bottleneck_#": "Domain Enclosure",
	"1_Labyrinth_DG_straight": "Domain Path",
	"1_Labyrinth_DG_straight_bottleneck": "Domain Path",
	"1_Labyrinth_DG_branch": "Domain Walkways",
	"1_Labyrinth_DG_branch_bottleneck_1_#": "Domain Walkways",
	"1_Labyrinth_DG_branch_bottleneck_2": "Domain Walkways",
	"1_Labyrinth_DG_branch_door": "Domain Walkways",
	"1_Labyrinth_DG_quad": "Domain Crossing",
	"1_Labyrinth_DG_quad_bottleneck": "Domain Crossing",
	"1_Labyrinth_DG_quad_door": "Domain Crossing",
	"1_Labyrinth_OH_end": "Estate Enclosure",
	"1_Labyrinth_OH_end_bottleneck": "Estate Enclosure",
	"1_Labyrinth_OH_straight": "Estate Path",
	"1_Labyrinth_OH_straight_bottleneck": "Estate Path",
	"1_Labyrinth_OH_branch": "Estate Walkways",
	"1_Labyrinth_OH_branch_bottleneck_1": "Estate Walkways",
	"1_Labyrinth_OH_branch_bottleneck_2": "Estate Walkways",
	"1_Labyrinth_OH_branch_door": "Estate Walkways",
	"1_Labyrinth_OH_quad_#": "Estate Crossing",
	"1_Labyrinth_OH_quad_bottleneck": "Estate Crossing",
	"1_Labyrinth_OH_quad_door_#": "Estate Crossing",
	"1_Labyrinth_boss_1": "Aspirant's Trial",
	"1_Labyrinth_boss_2": "Aspirant's Trial",
	"1_Labyrinth_boss_3": "Aspirant's Trial",
	"1_Labyrinth_boss_1_end": "Aspirant's Trial",
	"1_Labyrinth_boss_2_end": "Aspirant's Trial",
	"1_Labyrinth_boss_3_end_#": "Aspirant's Trial",
	"2_Labyrinth_C_end": "Sepulchre Annex",
	"2_Labyrinth_C_end_bottleneck": "Sepulchre Annex",
	"2_Labyrinth_C_straight": "Sepulchre Passage",
	"2_Labyrinth_C_straight_bottleneck": "Sepulchre Passage",
	"2_Labyrinth_C_branch": "Sepulchre Halls",
	"2_Labyrinth_C_branch_bottleneck_1": "Sepulchre Halls",
	"2_Labyrinth_C_branch_bottleneck_2": "Sepulchre Halls",
	"2_Labyrinth_C_branch_door": "Sepulchre Halls",
	"2_Labyrinth_C_quad": "Sepulchre Atrium",
	"2_Labyrinth_C_quad_bottleneck": "Sepulchre Atrium",
	"2_Labyrinth_C_quad_door": "Sepulchre Atrium",
	"2_Labyrinth_P_end": "Sanitorium Annex",
	"2_Labyrinth_P_end_bottleneck": "Sanitorium Annex",
	"2_Labyrinth_P_straight": "Sanitorium Passage",
	"2_Labyrinth_P_straight_bottleneck": "Sanitorium Passage",
	"2_Labyrinth_P_branch": "Sanitorium Halls",
	"2_Labyrinth_P_branch_bottleneck_1": "Sanitorium Halls",
	"2_Labyrinth_P_branch_bottleneck_2": "Sanitorium Halls",
	"2_Labyrinth_P_branch_door": "Sanitorium Halls",
	"2_Labyrinth_P_quad": "Sanitorium Atrium",
	"2_Labyrinth_P_quad_bottleneck": "Sanitorium Atrium",
	"2_Labyrinth_P_quad_door": "Sanitorium Atrium",
	"2_Labyrinth_EH_end": "Mansion Annex",
	"2_Labyrinth_EH_end_bottleneck": "Mansion Annex",
	"2_Labyrinth_EH_straight_#": "Mansion Passage",
	"2_Labyrinth_EH_straight_bottleneck": "Mansion Passage",
	"2_Labyrinth_EH_branch": "Mansion Halls",
	"2_Labyrinth_EH_branch_bottleneck_1": "Mansion Halls",
	"2_Labyrinth_EH_branch_bottleneck_2": "Mansion Halls",
	"2_Labyrinth_EH_branch_door": "Mansion Halls",
	"2_Labyrinth_EH_quad": "Mansion Atrium",
	"2_Labyrinth_EH_quad_bottleneck": "Mansion Atrium",
	"2_Labyrinth_EH_quad_door_#": "Mansion Atrium",
	"2_Labyrinth_RT_end": "Basilica Annex",
	"2_Labyrinth_RT_end_bottleneck": "Basilica Annex",
	"2_Labyrinth_RT_straight": "Basilica Passage",
	"2_Labyrinth_RT_straight_bottleneck": "Basilica Passage",
	"2_Labyrinth_RT_branch": "Basilica Halls",
	"2_Labyrinth_RT_branch_bottleneck_1": "Basilica Halls",
	"2_Labyrinth_RT_branch_bottleneck_2": "Basilica Halls",
	"2_Labyrinth_RT_branch_door": "Basilica Halls",
	"2_Labyrinth_RT_quad_#": "Basilica Atrium",
	"2_Labyrinth_RT_quad_bottleneck": "Basilica Atrium",
	"2_Labyrinth_RT_quad_door": "Basilica Atrium",
	"2_Labyrinth_DG_end": "Domain Enclosure",
	"2_Labyrinth_DG_end_bottleneck_#": "Domain Enclosure",
	"2_Labyrinth_DG_straight": "Domain Path",
	"2_Labyrinth_DG_straight_bottleneck": "Domain Path",
	"2_Labyrinth_DG_branch": "Domain Walkways",
	"2_Labyrinth_DG_branch_bottleneck_1_#": "Domain Walkways",
	"2_Labyrinth_DG_branch_bottleneck_2": "Domain Walkways",
	"2_Labyrinth_DG_branch_door": "Domain Walkways",
	"2_Labyrinth_DG_quad": "Domain Crossing",
	"2_Labyrinth_DG_quad_bottleneck": "Domain Crossing",
	"2_Labyrinth_DG_quad_door": "Domain Crossing",
	"2_Labyrinth_OH_end": "Estate Enclosure",
	"2_Labyrinth_OH_end_bottleneck": "Estate Enclosure",
	"2_Labyrinth_OH_straight": "Estate Path",
	"2_Labyrinth_OH_straight_bottleneck": "Estate Path",
	"2_Labyrinth_OH_branch": "Estate Walkways",
	"2_Labyrinth_OH_branch_bottleneck_1": "Estate Walkways",
	"2_Labyrinth_OH_branch_bottleneck_2": "Estate Walkways",
	"2_Labyrinth_OH_branch_door": "Estate Walkways",
	"2_Labyrinth_OH_quad_#": "Estate Crossing",
	"2_Labyrinth_OH_quad_bottleneck": "Estate Crossing",
	"2_Labyrinth_OH_quad_door_#": "Estate Crossing",
	"2_Labyrinth_boss_1": "Aspirant's Trial",
	"2_Labyrinth_boss_2": "Aspirant's Trial",
	"2_Labyrinth_boss_3": "Aspirant's Trial",
	"2_Labyrinth_boss_1_end": "Aspirant's Trial",
	"2_Labyrinth_boss_2_end": "Aspirant's Trial",
	"2_Labyrinth_boss_3_end_#": "Aspirant's Trial",
	"3_Labyrinth_C_end": "Sepulchre Annex",
	"3_Labyrinth_C_end_bottleneck": "Sepulchre Annex",
	"3_Labyrinth_C_straight": "Sepulchre Passage",
	"3_Labyrinth_C_straight_bottleneck": "Sepulchre Passage",
	"3_Labyrinth_C_branch": "Sepulchre Halls",
	"3_Labyrinth_C_branch_bottleneck_1": "Sepulchre Halls",
	"3_Labyrinth_C_branch_bottleneck_2": "Sepulchre Halls",
	"3_Labyrinth_C_branch_door": "Sepulchre Halls",
	"3_Labyrinth_C_quad": "Sepulchre Atrium",
	"3_Labyrinth_C_quad_bottleneck": "Sepulchre Atrium",
	"3_Labyrinth_C_quad_door": "Sepulchre Atrium",
	"3_Labyrinth_P_end": "Sanitorium Annex",
	"3_Labyrinth_P_end_bottleneck": "Sanitorium Annex",
	"3_Labyrinth_P_straight": "Sanitorium Passage",
	"3_Labyrinth_P_straight_bottleneck": "Sanitorium Passage",
	"3_Labyrinth_P_branch": "Sanitorium Halls",
	"3_Labyrinth_P_branch_bottleneck_1": "Sanitorium Halls",
	"3_Labyrinth_P_branch_bottleneck_2": "Sanitorium Halls",
	"3_Labyrinth_P_branch_door": "Sanitorium Halls",
	"3_Labyrinth_P_quad": "Sanitorium Atrium",
	"3_Labyrinth_P_quad_bottleneck": "Sanitorium Atrium",
	"3_Labyrinth_P_quad_door": "Sanitorium Atrium",
	"3_Labyrinth_EH_end": "Mansion Annex",
	"3_Labyrinth_EH_end_bottleneck": "Mansion Annex",
	"3_Labyrinth_EH_straight_#": "Mansion Passage",
	"3_Labyrinth_EH_straight_bottleneck": "Mansion Passage",
	"3_Labyrinth_EH_branch": "Mansion Halls",
	"3_Labyrinth_EH_branch_bottleneck_1": "Mansion Halls",
	"3_Labyrinth_EH_branch_bottleneck_2": "Mansion Halls",
	"3_Labyrinth_EH_branch_door": "Mansion Halls",
	"3_Labyrinth_EH_quad": "Mansion Atrium",
	"3_Labyrinth_EH_quad_bottleneck": "Mansion Atrium",
	"3_Labyrinth_EH_quad_door_#": "Mansion Atrium",
	"3_Labyrinth_RT_end": "Basilica Annex",
	"3_Labyrinth_RT_end_bottleneck": "Basilica Annex",
	"3_Labyrinth_RT_straight": "Basilica Passage",
	"3_Labyrinth_RT_straight_bottleneck": "Basilica Passage",
	"3_Labyrinth_RT_branch": "Basilica Halls",
	"3_Labyrinth_RT_branch_bottleneck_1": "Basilica Halls",
	"3_Labyrinth_RT_branch_bottleneck_2": "Basilica Halls",
	"3_Labyrinth_RT_branch_door": "Basilica Halls",
	"3_Labyrinth_RT_quad_#": "Basilica Atrium",
	"3_Labyrinth_RT_quad_bottleneck": "Basilica Atrium",
	"3_Labyrinth_RT_quad_door": "Basilica Atrium",
	"3_Labyrinth_DG_end": "Domain Enclosure",
	"3_Labyrinth_DG_end_bottleneck_#": "Domain Enclosure",
	"3_Labyrinth_DG_straight": "Domain Path",
	"3_Labyrinth_DG_straight_bottleneck": "Domain Path",
	"3_Labyrinth_DG_branch": "Domain Walkways",
	"3_Labyrinth_DG_branch_bottleneck_1_#": "Domain Walkways",
	"3_Labyrinth_DG_branch_bottleneck_2": "Domain Walkways",
	"3_Labyrinth_DG_branch_door": "Domain Walkways",
	"3_Labyrinth_DG_quad": "Domain Crossing",
	"3_Labyrinth_DG_quad_bottleneck": "Domain Crossing",
	"3_Labyrinth_DG_quad_door": "Domain Crossing",
	"3_Labyrinth_OH_end": "Estate Enclosure",
	"3_Labyrinth_OH_end_bottleneck": "Estate Enclosure",
	"3_Labyrinth_OH_straight": "Estate Path",
	"3_Labyrinth_OH_straight_bottleneck": "Estate Path",
	"3_Labyrinth_OH_branch": "Estate Walkways",
	"3_Labyrinth_OH_branch_bottleneck_1": "Estate Walkways",
	"3_Labyrinth_OH_branch_bottleneck_2": "Estate Walkways",
	"3_Labyrinth_OH_branch_door": "Estate Walkways",
	"3_Labyrinth_OH_quad_#": "Estate Crossing",
	"3_Labyrinth_OH_quad_bottleneck": "Estate Crossing",
	"3_Labyrinth_OH_quad_door_#": "Estate Crossing",
	"3_Labyrinth_boss_1": "Aspirant's Trial",
	"3_Labyrinth_boss_2": "Aspirant's Trial",
	"3_Labyrinth_boss_3": "Aspirant's Trial",
	"3_Labyrinth_boss_1_end": "Aspirant's Trial",
	"3_Labyrinth_boss_2_end_#": "Aspirant's Trial",
	"3_Labyrinth_boss_3_end": "Aspirant's Trial",
	"EndGame_Labyrinth_C_end": "Sepulchre Annex",
	"EndGame_Labyrinth_C_end_bottleneck": "Sepulchre Annex",
	"EndGame_Labyrinth_C_straight": "Sepulchre Passage",
	"EndGame_Labyrinth_C_straight_bottleneck": "Sepulchre Passage",
	"EndGame_Labyrinth_C_branch": "Sepulchre Halls",
	"EndGame_Labyrinth_C_branch_bottleneck_1": "Sepulchre Halls",
	"EndGame_Labyrinth_C_branch_bottleneck_2": "Sepulchre Halls",
	"EndGame_Labyrinth_C_branch_door": "Sepulchre Halls",
	"EndGame_Labyrinth_C_quad": "Sepulchre Atrium",
	"EndGame_Labyrinth_C_quad_bottleneck": "Sepulchre Atrium",
	"EndGame_Labyrinth_C_quad_door": "Sepulchre Atrium",
	"EndGame_Labyrinth_P_end": "Sanitorium Annex",
	"EndGame_Labyrinth_P_end_bottleneck": "Sanitorium Annex",
	"EndGame_Labyrinth_P_straight": "Sanitorium Passage",
	"EndGame_Labyrinth_P_straight_bottleneck": "Sanitorium Passage",
	"EndGame_Labyrinth_P_branch": "Sanitorium Halls",
	"EndGame_Labyrinth_P_branch_bottleneck_1": "Sanitorium Halls",
	"EndGame_Labyrinth_P_branch_bottleneck_2": "Sanitorium Halls",
	"EndGame_Labyrinth_P_branch_door": "Sanitorium Halls",
	"EndGame_Labyrinth_P_quad": "Sanitorium Atrium",
	"EndGame_Labyrinth_P_quad_bottleneck": "Sanitorium Atrium",
	"EndGame_Labyrinth_P_quad_door": "Sanitorium Atrium",
	"EndGame_Labyrinth_EH_end": "Mansion Annex",
	"EndGame_Labyrinth_EH_end_bottleneck": "Mansion Annex",
	"EndGame_Labyrinth_EH_straight_#": "Mansion Passage",
	"EndGame_Labyrinth_EH_straight_bottleneck": "Mansion Passage",
	"EndGame_Labyrinth_EH_branch": "Mansion Halls",
	"EndGame_Labyrinth_EH_branch_bottleneck_1": "Mansion Halls",
	"EndGame_Labyrinth_EH_branch_bottleneck_2": "Mansion Halls",
	"EndGame_Labyrinth_EH_branch_door": "Mansion Halls",
	"EndGame_Labyrinth_EH_quad": "Mansion Atrium",
	"EndGame_Labyrinth_EH_quad_bottleneck": "Mansion Atrium",
	"EndGame_Labyrinth_EH_quad_door_#": "Mansion Atrium",
	"EndGame_Labyrinth_RT_end": "Basilica Annex",
	"EndGame_Labyrinth_RT_end_bottleneck": "Basilica Annex",
	"EndGame_Labyrinth_RT_straight": "Basilica Passage",
	"EndGame_Labyrinth_RT_straight_bottleneck": "Basilica Passage",
	"EndGame_Labyrinth_RT_branch": "Basilica Halls",
	"EndGame_Labyrinth_RT_branch_bottleneck_1": "Basilica Halls",
	"EndGame_Labyrinth_RT_branch_bottleneck_2": "Basilica Halls",
	"EndGame_Labyrinth_RT_branch_door": "Basilica Halls",
	"EndGame_Labyrinth_RT_quad_#": "Basilica Atrium",
	"EndGame_Labyrinth_RT_quad_bottleneck": "Basilica Atrium",
	"EndGame_Labyrinth_RT_quad_door": "Basilica Atrium",
	"EndGame_Labyrinth_DG_end": "Domain Enclosure",
	"EndGame_Labyrinth_DG_end_bottleneck_#": "Domain Enclosure",
	"EndGame_Labyrinth_DG_straight": "Domain Path",
	"EndGame_Labyrinth_DG_straight_bottleneck": "Domain Path",
	"EndGame_Labyrinth_DG_branch": "Domain Walkways",
	"EndGame_Labyrinth_DG_branch_bottleneck_1_#": "Domain Walkways",
	"EndGame_Labyrinth_DG_branch_bottleneck_2": "Domain Walkways",
	"EndGame_Labyrinth_DG_branch_door": "Domain Walkways",
	"EndGame_Labyrinth_DG_quad": "Domain Crossing",
	"EndGame_Labyrinth_DG_quad_bottleneck": "Domain Crossing",
	"EndGame_Labyrinth_DG_quad_door": "Domain Crossing",
	"EndGame_Labyrinth_OH_end": "Estate Enclosure",
	"EndGame_Labyrinth_OH_end_bottleneck": "Estate Enclosure",
	"EndGame_Labyrinth_OH_straight": "Estate Path",
	"EndGame_Labyrinth_OH_straight_bottleneck": "Estate Path",
	"EndGame_Labyrinth_OH_branch": "Estate Walkways",
	"EndGame_Labyrinth_OH_branch_bottleneck_1": "Estate Walkways",
	"EndGame_Labyrinth_OH_branch_bottleneck_2": "Estate Walkways",
	"EndGame_Labyrinth_OH_branch_door": "Estate Walkways",
	"EndGame_Labyrinth_OH_quad_#": "Estate Crossing",
	"EndGame_Labyrinth_OH_quad_bottleneck": "Estate Crossing",
	"EndGame_Labyrinth_OH_quad_door_#": "Estate Crossing",
	"EndGame_Labyrinth_boss_1": "Aspirant's Trial",
	"EndGame_Labyrinth_boss_2": "Aspirant's Trial",
	"EndGame_Labyrinth_boss_3": "Aspirant's Trial",
	"EndGame_Labyrinth_boss_1_end": "Aspirant's Trial",
	"EndGame_Labyrinth_boss_2_end": "Aspirant's Trial",
	"EndGame_Labyrinth_boss_3_end": "Aspirant's Trial",
	"EndGame_Labyrinth_trials_sawblades_#": "Trial of Crippling Grief",
	"EndGame_Labyrinth_trials_lava_#": "Trial of Burning Rage",
	"EndGame_Labyrinth_trials_spinners": "Trial of Swirling Fear",
	"EndGame_Labyrinth_trials_spikes": "Trial of Piercing Truth",
	"EndGame_Labyrinth_trials_arrows": "Trial of Stinging Doubt",
	"EndGame_Labyrinth_trials_roombas": "Trial of Lingering Pain",
	"MapAtziri1": "The Apex of Sacrifice",
	"MapAtziri2": "The Alluring Abyss",
	"MapTier1_1": "Crypt",
	"MapTier1_1Unique": "The Coward's Trial",
	"MapTier1_2": "Dungeon",
	"MapTier1_3": "Grotto",
	"MapTier1_4": "Overgrown Ruin",
	"MapTier1_5": "Dunes",
	"MapTier1_6": "Arid Lake",
	"MapTier1_7": "Tropical Island",
	"MapTier1_7Unique": "Untainted Paradise",
	"MapTier1_8": "Orchard",
	"MapTier2_1": "Wharf",
	"MapTier2_2": "Arsenal",
	"MapTier2_3": "Thicket",
	"MapTier2_4": "Mountain Ledge",
	"MapTier2_4Unique": "Maelström of Chaos",
	"MapTier2_5": "Cemetery",
	"MapTier2_6": "Sewer",
	"MapTier2_7": "Arcade",
	"MapTier3_1": "Ghetto",
	"MapTier3_2": "Spider Lair",
	"MapTier3_3": "Vaal Pyramid",
	"MapTier3_3Unique": "Vaults of Atziri",
	"MapTier3_4": "Reef",
	"MapTier3_4Unique": "Mao Kun",
	"MapTier3_5": "Springs",
	"MapTier3_6": "Mud Geyser",
	"MapTier3_7": "Museum",
	"MapTier4_1": "Catacombs",
	"MapTier4_1Unique": "Convent of the Twins' Flame",
	"MapTier4_2": "Overgrown Shrine",
	"MapTier4_2Unique": "Acton's Nightmare",
	"MapTier4_3": "Tunnel",
	"MapTier4_4": "Shore",
	"MapTier4_5": "Spider Forest",
	"MapTier4_6": "Promenade",
	"MapTier4_6Unique": "The Hall of Grandmasters",
	"MapTier5_1": "Underground Sea",
	"MapTier5_2": "Pier",
	"MapTier5_3": "Bog",
	"MapTier5_4": "Graveyard",
	"MapTier5_5": "Coves",
	"MapTier5_6": "Villa",
	"MapTier6_1": "Temple",
	"MapTier6_1Unique": "Poorjoy's Asylum",
	"MapTier6_2": "Arachnid Nest",
	"MapTier6_3": "Strand",
	"MapTier6_3Unique": "Whakawairua Tuahu",
	"MapTier6_4": "Dry Woods",
	"MapTier6_5": "Colonnade",
	"MapTier6_5Unique": "Blackguard Salute",
	"MapTier7_1": "Torture Chamber",
	"MapTier7_1Unique": "Oba's Cursed Trove",
	"MapTier7_2": "Waste Pool",
	"MapTier7_3": "Abandoned Cavern",
	"MapTier7_4": "Jungle Valley",
	"MapTier7_5": "Terrace",
	"MapTier8_1": "Cells",
	"MapTier8_2": "Canyon",
	"MapTier8_3": "Dark Forest",
	"MapTier8_4": "Dry Peninsula",
	"MapTier9_1": "Underground River",
	"MapTier9_2": "Conservatory",
	"MapTier9_2Unique": "Olmec's Sanctum",
	"MapTier9_3": "Gorge",
	"MapTier9_4": "Residence",
	"MapTier10_1": "Necropolis",
	"MapTier10_1Unique": "Death and Taxes",
	"MapTier10_2": "Plateau",
	"MapTier10_3": "Bazaar",
	"MapTier11_1": "Crematorium",
	"MapTier11_2": "Precinct",
	"MapTier11_3": "Academy",
	"MapTier12_1": "Shipyard",
	"MapTier12_2": "Shrine",
	"MapTier12_2Unique": "Wraeclast Pantheon",
	"MapTier13_1": "Palace",
	"MapTier13_2": "Courtyard",
	"MapTier14_1": "Vaal Temple",
	"Map2Tier1_1": "Crypt",
	"Map2Tier1_1Unique": "The Coward's Trial",
	"Map2Tier1_2": "Dungeon",
	"Map2Tier1_3": "Grotto",
	"Map2Tier1_4": "Dunes",
	"Map2Tier1_5": "Pit",
	"Map2Tier1_6": "Tropical Island",
	"Map2Tier1_6Unique": "Untainted Paradise",
	"Map2Tier1_7": "Desert",
	"Map2Tier2_1": "Sewer",
	"Map2Tier2_2": "Channel",
	"Map2Tier2_3": "Thicket",
	"Map2Tier2_4": "Mountain Ledge",
	"Map2Tier2_4Unique": "Maelström of Chaos",
	"Map2Tier2_5": "Cemetery",
	"Map2Tier2_6": "Arcade",
	"Map2Tier2_7": "Wharf",
	"Map2Tier3_1": "Ghetto",
	"Map2Tier3_2": "Spider Lair",
	"Map2Tier3_3": "Vaal Pyramid",
	"Map2Tier3_3Unique": "Vaults of Atziri",
	"Map2Tier3_4": "Reef",
	"Map2Tier3_4Unique": "Mao Kun",
	"Map2Tier3_5": "Quarry",
	"Map2Tier3_6": "Mud Geyser",
	"Map2Tier3_7": "Museum",
	"Map2Tier4_1": "Arena",
	"Map2Tier4_2": "Overgrown Shrine",
	"Map2Tier4_2Unique": "Acton's Nightmare",
	"Map2Tier4_3": "Tunnel",
	"Map2Tier4_4": "Shore",
	"Map2Tier4_5": "Spider Forest",
	"Map2Tier4_6": "Promenade",
	"Map2Tier4_6Unique": "The Hall of Grandmasters",
	"Map2Tier4_7": "Phantasmagoria",
	"Map2Tier5_1": "Underground Sea",
	"Map2Tier5_1Unique": "Caer Blaidd, Wolfpack's Den",
	"Map2Tier5_2": "Pier",
	"Map2Tier5_3": "Bog",
	"Map2Tier5_4": "Graveyard",
	"Map2Tier5_5": "Coves",
	"Map2Tier5_6": "Villa",
	"Map2Tier6_1": "Temple",
	"Map2Tier6_1Unique": "Poorjoy's Asylum",
	"Map2Tier6_2": "Arachnid Nest",
	"Map2Tier6_3": "Strand",
	"Map2Tier6_3Unique": "Whakawairua Tuahu",
	"Map2Tier6_4_": "Dry Woods",
	"Map2Tier6_5": "Colonnade",
	"Map2Tier6_5Unique": "Blackguard Salute",
	"Map2Tier6_6": "Catacombs",
	"Map2Tier6_6Unique": "Olmec's Sanctum",
	"Map2Tier7_1": "Torture Chamber",
	"Map2Tier7_1Unique": "Oba's Cursed Trove",
	"Map2Tier7_2": "Waste Pool",
	"Map2Tier7_3": "Abandoned Cavern",
	"Map2Tier7_4": "Jungle Valley",
	"Map2Tier7_5": "Terrace",
	"Map2Tier8_1": "Cells",
	"Map2Tier8_2": "Canyon",
	"Map2Tier8_3": "Dark Forest",
	"Map2Tier8_4": "Dry Peninsula",
	"Map2Tier8_5": "Orchard",
	"Map2Tier9_1": "Underground River",
	"Map2Tier9_2": "Arid Lake",
	"Map2Tier9_3": "Gorge",
	"Map2Tier9_4": "Residence",
	"Map2Tier9_5": "Malformation",
	"Map2Tier10_1": "Necropolis",
	"Map2Tier10_1Unique": "Death and Taxes",
	"Map2Tier10_2": "Plateau",
	"Map2Tier10_3": "Bazaar",
	"Map2Tier10_4": "Volcano",
	"Map2Tier10_5": "Chateau",
	"Map2Tier10_5Unique": "Perandus Manor",
	"Map2Tier11_1": "Crematorium",
	"Map2Tier11_2": "Precinct",
	"Map2Tier11_3": "Academy",
	"Map2Tier11_4": "Springs",
	"Map2Tier12_1": "Shipyard",
	"Map2Tier12_2": "Overgrown Ruin",
	"Map2Tier12_3": "Village Ruin",
	"Map2Tier12_4": "Arsenal",
	"Map2Tier13_1": "Wasteland",
	"Map2Tier13_2": "Courtyard",
	"Map2Tier13_2Unique": "The Vinktar Square",
	"Map2Tier13_3": "Excavation",
	"Map2Tier13_4": "Waterways",
	"Map2Tier14_1": "Palace",
	"Map2Tier14_2": "Shrine",
	"Map2Tier14_2Unique": "Wraeclast Pantheon",
	"Map2Tier14_3": "Conservatory",
	"Map2Tier14_4": "Vaal Temple",
	"Map2Tier14_5": "Plaza",
	"Map2Tier15_1": "Core",
	"Map2Tier15_2": "Abyss",
	"Map2Tier15_3": "Colosseum",
	"ffa1_1": "Sarn Arena",
	"ffa2_1": "Sarn Arena",
	"ffa3_1": "Sarn Arena",
	"pvp1": "PvP 1v1 Arena",
	"pvp2": "PvP 2v2 Arena",
	"pvp3": "PvP Large Arena",
	"pvp1Cruel": "PvP 1v1 Arena",
	"pvp3Cruel": "PvP Large Arena",
	"pvp1Open": "PvP 1v1 Arena",
	"pvp2Open": "PvP 2v2 Arena",
	"pvp3Open": "PvP Large Arena",
	"pvpBlitz": "PvP Blitz Arena",
	"PetFlats": "PetFlats",
	"Descent1": "The Phrecia Outskirts",
	"Descent2": "The Heart of Phrecia",
	"Descent3": "The Lost Cathedral",
	"Descent4": "The Mortal Tomb",
	"Descent5": "The Arachnid Tomb",
	"Descent6": "The Tomb of Statues",
	"Descent7": "The Frozen Abyss",
	"Descent8": "The Simian Cave",
	"Descent9": "The Skeletal Caverns",
	"Descent10": "The Forbidden Ruins",
	"Descent11": "The Vault of the Guardians",
	"Descent12": "The Hall of Heroes",
	"Descent13": "The Desecrated Shrine",
	"Descent14": "The Demonic Shrine",
	"Descent15": "The Infernal Shrine",
	"Descent2_1": "The Entrance Hall",
	"Descent2_2_1": "The Chattering Halls",
	"Descent2_2_2": "The Croaking Halls",
	"Descent2_3": "The Rasping Halls",
	"Descent2_3_side1": "The Freezing Chamber",
	"Descent2_3_boss": "The Shrine of the Pagan God",
	"Descent2_4": "The Dungeon of Anarchy",
	"Descent2_5_1": "The Dungeon of Necromancy",
	"Descent2_5_2": "The Hollow Cave",
	"Descent2_6_1": "The Haunted Dungeon",
	"Descent2_6_1_side1": "The Obelisks of Faith",
	"Descent2_6_2": "The Burning Cave",
	"Descent2_6_2_side1": "The Chamber of Greed",
	"Descent2_6_boss": "The Cage",
	"Descent2_7": "The Necromantic Crypt",
	"Descent2_8_1": "The Diabolic Crypt",
	"Descent2_8_2": "The Misty Cave",
	"Descent2_9_1": "The Ember Crypt",
	"Descent2_9_2": "The Stormy Ledge",
	"Descent2_9_3": "The Frozen Cave",
	"Descent2_9_boss1": "The Glittering Crypt",
	"Descent2_9_boss2": "The Glittering Cave",
	"Descent2_10": "The Inner Halls Level 1",
	"Descent2_11": "The Inner Halls Level 2",
	"Descent2_12": "The Inner Halls Level 3",
	"Descent2_12_boss": "The Nexus",
	"ctf1": "PvP 1v1 Capture the Flag",
	"ctf2": "PvP 2v2 Capture the Flag",
	"ctf3": "PvP 3v3 Capture the Flag",
	"ctf4": "PvP 6v6 Capture the Flag",
	"ctf3open": "PvP 3v3 Capture the Flag",
	"ctf4open": "PvP 6v6 Capture the Flag",
	"ctf5": "PvP 1v1v1 Capture the Flag",
	"ctf6": "PvP 2v2v2 Capture the Flag",
	"ctf7": "PvP 3v3v3 Capture the Flag",
	"ctf8": "PvP 6v6v6 Capture the Flag",
	"EndlessLedge1": "The Endless Ledge",
	"EndlessLedge2": "The Endless Ledge",
	"EndlessLedge3": "The Endless Ledge",
	"MapEndlessLedge4": "The Endless Ledge",
	"MapEndlessLedge5": "The Endless Ledge",
	"MapEndlessLedge6": "The Endless Ledge",
	"MapEndlessLedge7": "The Endless Ledge",
	"MapEndlessLedge8": "The Endless Ledge",
	"MapEndlessLedge9": "The Endless Ledge",
	"MapEndlessLedge10": "The Endless Ledge",
	"MapEndlessLedge11": "The Endless Ledge",
	"MapEndlessLedge12": "The Endless Ledge",
	"MapEndlessLedge13": "The Endless Ledge",
	"MapEndlessLedge14": "The Endless Ledge",
	"MapEndlessLedge15": "The Endless Ledge",
	"MapEndlessLedge16": "The Endless Ledge",
	"MapEndlessLedge17": "The Endless Ledge",
	"MapEndlessLedge18": "The Endless Ledge",
	"MapEndlessLedge19": "The Endless Ledge",
	"MapEndlessLedge20": "The Endless Ledge",
	"MapEndlessLedge21": "The Endless Ledge",
	"MapEndlessLedge22": "The Endless Ledge",
	"MapEndlessLedge23": "The Endless Ledge",
	"MapEndlessLedge24": "The Endless Ledge",
	"MapEndlessLedge25": "The Endless Ledge",
	"MapEndlessLedge26": "The Endless Ledge",
	"MapEndlessLedge27": "The Endless Ledge",
	"MapEndlessLedge28": "The Endless Ledge",
	"MapEndlessLedge29": "The Endless Ledge",
	"MapEndlessLedge30": "The Endless Ledge",
	"MapEndlessLedge31": "The Endless Ledge",
	"MapEndlessLedge32": "The Endless Ledge",
	"MapEndlessLedge33": "The Endless Ledge",
	"MapEndlessLedge34": "The Endless Ledge",
	"MapEndlessLedge35": "The Endless Ledge",
	"MapEndlessLedge36": "The Endless Ledge",
	"MapEndlessLedge37": "The Endless Ledge",
	"MapEndlessLedge38": "The Endless Ledge",
	"MapEndlessLedge39": "The Endless Ledge",
	"MapEndlessLedge40": "The Endless Ledge",
	"MapEndlessLedge41": "The Endless Ledge",
	"MapEndlessLedge42": "The Endless Ledge",
	"MapEndlessLedge43": "The Endless Ledge",
	"MapEndlessLedge44": "The Endless Ledge",
	"MapEndlessLedge45": "The Endless Ledge",
	"MapEndlessLedge46": "The Endless Ledge",
	"MapEndlessLedge47": "The Endless Ledge",
	"MapEndlessLedge48": "The Endless Ledge",
	"MapEndlessLedge49": "The Endless Ledge",
	"MapEndlessLedge50": "The Endless Ledge",
	"MapEndlessLedge51": "The Endless Ledge",
	"MapEndlessLedge52": "The Endless Ledge",
	"MapEndlessLedge53": "The Endless Ledge",
	"MapEndlessLedge54": "The Endless Ledge",
	"MapEndlessLedge55": "The Endless Ledge",
	"MapEndlessLedge56": "The Endless Ledge",
	"MapEndlessLedge57": "The Endless Ledge",
	"MapEndlessLedge58": "The Endless Ledge",
	"MapEndlessLedge59": "The Endless Ledge",
	"MapEndlessLedge60": "The Endless Ledge",
	"MapEndlessLedge61": "The Endless Ledge",
	"MapEndlessLedge62": "The Endless Ledge",
	"MapEndlessLedge63": "The Endless Ledge",
	"MapEndlessLedge64": "The Endless Ledge",
	"MapEndlessLedge65": "The Endless Ledge",
	"MapEndlessLedge66": "The Endless Ledge",
	"MapEndlessLedge67": "The Endless Ledge",
	"MapEndlessLedge68": "The Endless Ledge",
	"MapEndlessLedge69": "The Endless Ledge",
	"MapEndlessLedge70": "The Endless Ledge",
	"MapEndlessLedge71": "The Endless Ledge",
	"MapEndlessLedge72": "The Endless Ledge",
	"MapEndlessLedge73": "The Endless Ledge",
	"MapEndlessLedge74": "The Endless Ledge",
	"MapEndlessLedge75": "The Endless Ledge",
	"MapEndlessLedge76": "The Endless Ledge",
	"MapEndlessLedge77": "The Endless Ledge",
	"MapEndlessLedge78": "The Endless Ledge",
	"MapEndlessLedge79": "The Endless Ledge",
	"MapEndlessLedge80": "The Endless Ledge",
	"MapEndlessLedge81": "The Endless Ledge",
	"MapEndlessLedge82": "The Endless Ledge",
	"MapEndlessLedge83": "The Endless Ledge",
	"MapEndlessLedge84": "The Endless Ledge",
	"MapEndlessLedge85": "The Endless Ledge",
	"MapEndlessLedge86": "The Endless Ledge",
	"MapEndlessLedge87": "The Endless Ledge",
	"MapEndlessLedge88": "The Endless Ledge",
	"MapEndlessLedge89": "The Endless Ledge",
	"MapEndlessLedge90": "The Endless Ledge",
	"MapEndlessLedge91": "The Endless Ledge",
	"MapEndlessLedge92": "The Endless Ledge",
	"MapEndlessLedge93": "The Endless Ledge",
	"MapEndlessLedge94": "The Endless Ledge",
	"MapEndlessLedge95": "The Endless Ledge",
	"MapEndlessLedge96": "The Endless Ledge",
	"MapEndlessLedge97": "The Endless Ledge",
	"MapEndlessLedge98": "The Endless Ledge",
	"MapEndlessLedge99": "The Endless Ledge",
	"MapEndlessLedge100": "The Endless Ledge",
	"Hideout1_1": "Battle-scarred Hideout",
	"Hideout1_2": "Battle-scarred Hideout",
	"Hideout1_3": "Battle-scarred Hideout",
	"Hideout2_1": "Baleful Hideout",
	"Hideout2_2": "Baleful Hideout",
	"Hideout2_3": "Baleful Hideout",
	"Hideout3_1": "Undercity Hideout",
	"Hideout3_2": "Undercity Hideout",
	"Hideout3_3": "Undercity Hideout",
	"Hideout4_1": "Cavernous Hideout",
	"Hideout4_2": "Cavernous Hideout",
	"Hideout4_3": "Cavernous Hideout",
	"Hideout5_1": "Forsaken Hideout",
	"Hideout5_2": "Forsaken Hideout",
	"Hideout5_3": "Forsaken Hideout",
	"Hideout6_1": "Coastal Hideout",
	"Hideout6_2": "Coastal Hideout",
	"Hideout6_3": "Coastal Hideout",
	"Hideout7_1": "Lush Hideout",
	"Hideout7_2": "Lush Hideout",
	"Hideout7_3": "Lush Hideout",
	"Hideout8_1": "Enlightened Hideout",
	"Hideout8_2": "Enlightened Hideout",
	"Hideout8_3": "Enlightened Hideout",
	"Hideout9_1": "Overgrown Hideout",
	"Hideout9_2": "Overgrown Hideout",
	"Hideout9_3": "Overgrown Hideout",
	"Hideout10_1": "Immaculate Hideout",
	"Hideout10_2": "Immaculate Hideout",
	"Hideout10_3": "Immaculate Hideout",
	"Hideout11_1": "Bloodsoaked Hideout",
	"Hideout11_2": "Bloodsoaked Hideout",
	"Hideout11_3": "Bloodsoaked Hideout",
	"Hideout12_1": "Downtown Hideout",
	"Hideout12_2": "Downtown Hideout",
	"Hideout12_3": "Downtown Hideout",
	"Hideout13_1": "Lofty Hideout",
	"Hideout13_2": "Lofty Hideout",
	"Hideout13_3": "Lofty Hideout",
	"Hideout14_1": "Unearthed Hideout",
	"Hideout14_2": "Unearthed Hideout",
	"Hideout14_3": "Unearthed Hideout",
	"Hideout15_1": "Backstreet Hideout",
	"Hideout15_2": "Backstreet Hideout",
	"Hideout15_3": "Backstreet Hideout",
	"Hideout16_1": "Stockroom Hideout",
	"Hideout16_2": "Stockroom Hideout",
	"Hideout16_3": "Stockroom Hideout",
	"Hideout17_1": "Industrial Hideout",
	"Hideout17_2": "Industrial Hideout",
	"Hideout17_3": "Industrial Hideout",
	"Hideout24_1": "HideoutShip1",
	"Hideout61_1": "Winding Pier",
	"Hideout61_2": "Winding Pier",
	"Hideout61_3": "Winding Pier",
	"pvpTown": "Sarn Arena Staging Area",
	"AnimTest": "Animation Test Area",
	"LightTest": "Light Test",
	"PortalLeagueTest": "Rhoa Fight",
	"ArrowTest": "Arrow Test",
	"RoomTest": "RoomTest"
}

module.exports = {
	soundtrack: soundtrack,
	worldAreas : worldAreas
}
