let soundtrack = {
	"tracks": [
	    {"name": "options", "location": "https://www.youtube.com/watch?v=AoTDngh-d2E"},
	    {"name": "rogue_encampment", "location": "https://www.youtube.com/watch?v=t1Zf9w--VhM"},
	    {"name": "wild", "location": "https://www.youtube.com/watch?v=LEKoC5s6150"},
	    {"name": "tristram", "location": "https://www.youtube.com/watch?v=8nl4KeCiEtQ"},
	    {"name": "monastery", "location": "https://www.youtube.com/watch?v=HvMeIJOqrhg"},
	    {"name": "caves", "location": "https://www.youtube.com/watch?v=0Zd0zDnTCoM"},
	    {"name": "crypt", "location": "https://www.youtube.com/watch?v=U2eHs-C1828"},

	    {"name": "lut_gholein", "location": "https://www.youtube.com/watch?v=OmdXk3jJsB0"},
	    {"name": "desert", "location": "https://www.youtube.com/watch?v=mseOvWsn55w"},
	    {"name": "valley", "location": "https://www.youtube.com/watch?v=PYe_Dd48Mcs"},
	    {"name": "sewer", "location": "https://www.youtube.com/watch?v=LH_F9SshwIw"},
	    {"name": "tombs", "location": "https://www.youtube.com/watch?v=YnSKVIH4_3k"},
	    {"name": "lair", "location": "https://www.youtube.com/watch?v=MbyhMeB10t8"},
	    {"name": "harem", "location": "https://www.youtube.com/watch?v=ub_Igr_L-rw"},
	    {"name": "sanctuary", "location": "https://www.youtube.com/watch?v=CoTRxDhyzms"},

	    {"name": "kurast_docks", "location": "https://www.youtube.com/watch?v=OehozBDOF_Q"},
	    {"name": "jungle", "location": "https://www.youtube.com/watch?v=3ZXLsl2qazQ"},
	    {"name": "kurast", "location": "https://www.youtube.com/watch?v=bwPNeWUSjKQ"},
	    {"name": "spider", "location": "https://www.youtube.com/watch?v=Ocp7GyhyeTo"},
	    {"name": "kurast_sewers", "location": "https://www.youtube.com/watch?v=AvfZRdGZstA"},

	    {"name": "pandemonium_fortress", "location": "https://www.youtube.com/watch?v=v2XzZZI0f48"},
	    {"name": "mesa", "location": "https://www.youtube.com/watch?v=qlIBDL_W8xo"},
	    {"name": "diablo", "location": "https://www.youtube.com/watch?v=n041TsHeJi8"},

	    {"name": "intro", "location": "https://www.youtube.com/watch?v=LngkyTYbLrk"},
	    {"name": "harrogath", "location": "https://www.youtube.com/watch?v=layjWs2IpS4"},
	    {"name": "siege", "location": "https://www.youtube.com/watch?v=HylopY97ALc"},
	    {"name": "ice_caves", "location": "https://www.youtube.com/watch?v=hMppfXwvVoM"},
	    {"name": "temple", "location": "https://www.youtube.com/watch?v=YuTE61U3iJM"},
	    {"name": "baal", "location": "https://www.youtube.com/watch?v=xcuz5IofwKo"},
	 ],

	"map":	{
	    "login": "intro",
	    "Lioneye's Watch": "rogue_encampment",
	    "The Twilight Strand": "wild",
	    "The Coast": "wild",
	    "The Tidal Island": "wild",
	    "The Mud Flats": "wild",
	    "The Fetid Pool": "caves",
	    "The Flooded Depths": "caves",
	    "The Submerged Passage": "caves",
	    "The Ledge": "wild",
	    "The Climb": "wild",
	    "The Lower Prison": "monastery",
	    "The Upper Prison": "monastery",
	    "Prisoner's Gate": "wild",
	    "The Ship Graveyard": "tristram",
	    "The Ship Graveyard Cave": "tristram",
	    "The Cavern of Wrath": "crypt",
	    "The Cavern of Anger": "crypt",
	    "The Forest Encampment": "kurast_docks",
	    "The Southern Forest": "jungle",
	    "The Old Fields": "jungle",
	    "The Den": "spider",
	    "The Crossroads": "jungle",
	    "The Crypt Level 1": "kurast_sewers",
	    "The Crypt Level 2": "kurast_sewers",
	    "The Chamber of Sins Level 1": "kurast_sewers",
	    "The Chamber of Sins Level 2": "kurast_sewers",
	    "The Broken Bridge": "kurast",
	    "The Riverways": "jungle",
	    "The Northern Forest": "jungle",
	    "The Western Forest": "jungle",
	    "The Weaver's Chambers": "spider",
	    "The Vaal Ruins": "kurast_sewers",
	    "The Wetlands": "jungle",
	    "The Dread Thicket": "jungle",
	    "The Caverns": "kurast_sewers",
	    "The Ancient Pyramid": "kurast_sewers",
	    "The Fellshrine Ruins": "kurast",
	    "The Sarn Encampment": "lut_gholein",
	    "The City of Sarn": "desert",
	    "The Slums": "desert",
	    "The Crematorium": "tombs",
	    "The Marketplace": "desert",
	    "The Catacombs": "tombs",
	    "The Battlefront": "valley",
	    "The Solaris Temple Level 1": "harem",
	    "The Solaris Temple Level 2": "harem",
	    "The Docks": "valley",
	    "The Sewers": "random",
	    "The Ebony Barracks": "valley",
	    "The Lunaris Temple Level 1": "harem",
	    "The Lunaris Temple Level 2": "harem",
	    "The Imperial Gardens": "valley",
	    "The Library": "sanctuary",
	    "The Archives": "sanctuary",
	    "The Sceptre of God": "tombs",
	    "The Upper Sceptre of God": "tombs",
	    "Highgate": "pandemonium_fortress",
	    "The Aqueduct": "mesa",
	    "The Dried Lake": "mesa",
	    "The Mines Level 1": "lair",
	    "The Mines Level 2": "lair",
	    "The Crystal Veins": "lair",
	    "Kaom's Dream": "mesa",
	    "Kaom's Stronghold": "mesa",
	    "Daresso's Dream": "mesa",
	    "The Grand Arena": "mesa",
	    "The Belly of the Beast Level 1": "diablo",
	    "The Belly of the Beast Level 2": "diablo",
	    "The Harvest": "diablo",
	    "The Ascent": "intro",
	    "The Slave Pens": "siege",
	    "Overseer's Tower": "harrogath",
	    "The Control Blocks": "siege",
	    "Oriath Square": "siege",
	    "The Ruined Square": "siege",
	    "The Templar Courts": "temple",
	    "The Torched Courts": "temple",
	    "The Chamber of Innocence": "baal",
	    "The Ossuary": "ice_caves",
	    "The Reliquary": "ice_caves",
	    "The Cathedral Rooftop": "baal",
	    "The Karui Fortress": "tristram",
	    "The Ridge": "wild",
	    "Shavronne's Tower": "monastery",
	    "The Beacon": "tristram",
	    "The Brine King's Reef": "crypt",
	    "The Bridge Encampment": "kurast_docks",
	    "The Crypt": "kurast_sewers",
	    "Maligaro's Sanctum": "harem",
	    "The Ashen Fields": "jungle",
	    "The Causeway": "kurast",
	    "The Vaal City": "kurast_sewers",
	    "The Temple of Decay Level 1": "spider",
	    "The Temple of Decay Level 2": "spider",
	    "The Sarn Ramparts": "desert",
	    "The Toxic Conduits": "sewer",
	    "Doedre's Cesspool": "sewer",
	    "The Grand Promenade": "valley",
	    "The High Gardens": "sanctuary",
	    "The Bath House": "harem",
	    "The Lunaris Concourse": "tombs",
	    "The Quay": "valley",
	    "The Grain Gate": "valley",
	    "The Imperial Fields": "desert",
	    "The Solaris Concourse": "tombs",
	    "The Harbour Bridge": "sanctuary",
	    "The Blood Aqueduct": "mesa",
	    "The Descent": "intro",
	    "The Vastiri Desert": "desert",
	    "The Oasis": "desert",
	    "The Foothills": "siege",
	    "The Boiling Lake": "wild",
	    "The Tunnel": "lair",
	    "The Quarry": "mesa",
	    "The Refinery": "lair",
	    "The Belly of the Beast": "diablo",
	    "The Rotting Core": "diablo",
	    "Oriath Docks": "harrogath",
	    "The Ravaged Square": "siege",
	    "The Desecrated Chambers": "siege",
	    "The Canals": "baal",
	    "The Feeding Trough": "baal",
	    "Oriath": "options",
	    "The Templar Laboratory": "options",
		"The Atlas of Worlds": "random",
		"Karui Shores": "harrogath",
		"The Fallen Courts": "random",
		"The Haunted Reliquary": "random",
		"The Eternal Laboratory": "random",
		"Strange Sinkhole": "random",
		"Concealed Cavity": "random",
		"Sunken Shingle": "random",
		"Clouded Ridge": "random",
		"Forgotten Oubliette": "random",
		"Remote Gulch": "random",
		"Narrow Ravine": "random",
		"Mystical Clearing": "random",
		"Covered-up Hollow": "random",
		"Hidden Patch": "random",
		"Entombed Alcove": "random",
		"Secret Laboratory": "random",
		"Secluded Copse": "random",
		"Forbidden Chamber": "random",
		"Quarantined Quarters": "random",
		"Disused Furnace": "random",
		"Blind Alley": "random",
		"Entombed Chamber": "random",
		"Sacred Chambers": "random",
		"Stagnant Canal": "random",
		"Walled-off Ducts": "random",
		"Neglected Cellar": "random",
		"Arcane Chambers": "random",
		"Inner Grounds": "random",
		"Sealed Corridors": "random",
		"Restricted Gallery": "random",
		"Forgotten Conduit": "random",
		"Ancient Catacomb": "random",
		"Haunted Mineshaft": "random",
		"Abandoned Dam": "random",
		"Desolate Track": "random",
		"Reclaimed Barracks": "random",
		"Sealed Basement": "random",
		"Secluded Canal": "random",
		"Forbidden Archives": "random",
		"Cremated Archives": "random",
		"Twisted Inquisitorium": "random",
		"Deathly Chambers": "random",
		"Restricted Collection": "random",
		"Side Chapel": "random",
		"Radiant Pools": "random",
		"Clouded Ledge": "random",
		"Sealed Repository": "random",
		"Flooded Complex": "random",
		"Forbidden Shrine": "random",
		"Evacuated Quarter": "random",
		"Concealed Caldarium": "random",
		"Moonlit Chambers": "random",
		"Shifting Sands": "random",
		"Forgotten Gulch": "random",
		"Desolate Isle": "random",
		"Dusty Bluff": "random",
		"Lair of the Wolven King": "random",
		"The Pale Court": "random",
		"Ancient Reliquary": "random",
		"Timeworn Reliquary": "random",
		"The Menagerie": "random",
		"Menagerie Wilds": "random",
		"Menagerie Sands": "random",
		"Menagerie Caverns": "random",
		"Menagerie Depths": "random",
		"The Temple of Atzoatl": "random",
		"Incursion Room": "random",
		"Azurite Mine Encampment": "random",
		"Azurite Mine": "random",
		"Fungal Caverns": "random",
		"Petrified Forest": "random",
		"Abyssal Depths": "random",
		"Frozen Hollow": "random",
		"Magma Fissure": "random",
		"Sulphur Vents": "random",
		"Vaal Outpost": "random",
		"Abyssal Span": "random",
		"Primeval Fortress": "random",
		"Vaal Nexus": "random",
		"Abyssal Sanctum": "random",
		"Primeval Citadel": "random",
		"Vaal Ruined Chamber": "random",
		"Primeval Chamber": "random",
		"Abyssal Chamber": "random",
		"The Forbidden Vault": "random",
		"Syndicate Laboratory": "random",
		"Syndicate Hideout": "random",
		"Mastermind's Lair": "random",
		"Memory Void": "random",
		"Fragmented Memory": "random",
		"Memory Nexus": "random",
		"Fractured Laboratory": "random",
		"Distant Memory": "random",
		"Shattered Memory": "random",
        "Altered Distant Memory": "random",
        "Augmented Distant Memory": "random",
        "Rewritten Distant Memory": "random",
        "Twisted Distant Memory": "random",
        "Cortex": "random",
		"Tane's Laboratory": "random",
		"Aspirants' Plaza": "random",
		"Sepulchre Annex": "random",
		"Sepulchre Passage": "random",
		"Sepulchre Halls": "random",
		"Sepulchre Atrium": "random",
		"Sanitorium Annex": "random",
		"Sanitorium Passage": "random",
		"Sanitorium Halls": "random",
		"Sanitorium Atrium": "random",
		"Mansion Annex": "random",
		"Mansion Passage": "random",
		"Mansion Halls": "random",
		"Mansion Atrium": "random",
		"Basilica Annex": "random",
		"Basilica Passage": "random",
		"Basilica Halls": "random",
		"Basilica Atrium": "random",
		"Domain Enclosure": "random",
		"Domain Path": "random",
		"Domain Walkways": "random",
		"Domain Crossing": "random",
		"Estate Enclosure": "random",
		"Estate Path": "random",
		"Estate Walkways": "random",
		"Estate Crossing": "random",
		"Aspirant's Trial": "random",
		"Trial of Crippling Grief": "random",
		"Trial of Burning Rage": "random",
		"Trial of Swirling Fear": "random",
		"Trial of Piercing Truth": "random",
		"Trial of Stinging Doubt": "random",
		"Trial of Lingering Pain": "random",
		"The Apex of Sacrifice": "random",
		"The Alluring Abyss": "random",
		"Cursed Crypt": "random",
		"The Coward's Trial": "random",
		"Dungeon": "random",
		"Grotto": "random",
		"Overgrown Ruin": "random",
		"Dunes": "random",
		"Arid Lake": "random",
		"Tropical Island": "random",
		"Untainted Paradise": "random",
		"Orchard": "random",
		"Wharf": "random",
		"Arsenal": "random",
		"Thicket": "random",
		"Atoll": "random",
		"Maelström of Chaos": "random",
		"Cemetery": "random",
		"Toxic Sewer": "random",
		"Arcade": "random",
		"Ghetto": "random",
		"Spider Lair": "random",
		"Vaal Pyramid": "random",
		"Vaults of Atziri": "random",
		"Reef": "random",
		"Mao Kun": "random",
		"Fungal Hollow": "random",
		"Mud Geyser": "random",
		"Museum": "random",
		"Bone Crypt": "random",
		"Convent of the Twins' Flame": "random",
		"Overgrown Shrine": "random",
		"Acton's Nightmare": "random",
		"Crystal Ore": "random",
		"Shore": "random",
		"Spider Forest": "random",
		"Promenade": "random",
		"The Hall of Grandmasters": "random",
		"Underground River": "random",
		"Pier": "random",
		"Bog": "random",
		"Graveyard": "random",
		"Coves": "random",
		"Villa": "random",
		"Temple": "random",
		"Poorjoy's Asylum": "random",
		"Arachnid Nest": "random",
		"Strand": "random",
		"Whakawairua Tuahu": "random",
		"Ashen Wood": "random",
		"Colonnade": "random",
		"Blackguard Salute": "random",
		"Primordial Blocks": "random",
		"Oba's Cursed Trove": "random",
		"Waste Pool": "random",
		"Flooded Mine": "random",
		"Jungle Valley": "random",
		"Gardens": "random",
		"Cells": "random",
		"Canyon": "random",
		"Dark Forest": "random",
		"Peninsula": "random",
		"Underground Sea": "random",
		"Maze": "random",
		"Olmec's Sanctum": "random",
		"Glacier": "random",
		"Residence": "random",
		"Necropolis": "random",
		"Death and Taxes": "random",
		"Plateau": "random",
		"Bazaar": "random",
		"Lava Chamber": "random",
		"Precinct": "random",
		"Academy": "random",
		"Shipyard": "random",
		"Shrine": "random",
		"Wraeclast Pantheon": "random",
		"Palace": "random",
		"Courtyard": "random",
		"Vaal Temple": "random",
		"Pit": "random",
		"Desert": "random",
		"Channel": "random",
		"Geode": "random",
		"Arena": "random",
		"Phantasmagoria": "random",
		"Caer Blaidd, Wolfpack's Den": "random",
		"Malformation": "random",
		"Volcano": "random",
		"Chateau": "random",
		"Perandus Manor": "random",
		"Castle Ruins": "random",
		"Wasteland": "random",
		"The Vinktar Square": "random",
		"Excavation": "random",
		"Waterways": "random",
		"Plaza": "random",
		"Core": "random",
		"Caldera": "random",
		"Colosseum": "random",
		"Hallowed Ground": "random",
		"Beach": "random",
		"Factory": "random",
		"Desert Spring": "random",
		"Marshes": "random",
		"The Putrid Cloister": "random",
		"Acid Caverns": "random",
		"Burial Chambers": "random",
		"Mesa": "random",
		"Darbel's Promise": "random",
		"Primordial Pool": "random",
		"Tower": "random",
		"Racecourse": "random",
		"Ramparts": "random",
		"Ancient City": "random",
		"Arachnid Tomb": "random",
		"Armoury": "random",
		"Barrows": "random",
		"Port": "random",
		"Estuary": "random",
		"Ivory Temple": "random",
		"Vault": "random",
		"Lair": "random",
		"Lighthouse": "random",
		"Terrace": "random",
		"Scriptorium": "random",
		"Leyline": "random",
		"Mineral Pools": "random",
		"Pit of the Chimera": "random",
		"Lair of the Hydra": "random",
		"Forge of the Phoenix": "random",
		"Maze of the Minotaur": "random",
		"The Shaper's Realm": "random",
		"Uul-Netol's Domain": "random",
		"Chayula's Domain": "random",
		"Xoph's Domain": "random",
		"Tul's Domain": "random",
		"Esh's Domain": "random",
		"Harbinger's Isle": "random",
		"The Beachhead": "random",
		"Lookout": "random",
		"Alleyways": "random",
		"Pen": "random",
		"Iceberg": "random",
		"Cage": "random",
		"City Square": "random",
		"Relic Chambers": "random",
		"Courthouse": "random",
		"Conservatory": "random",
		"Haunted Mansion": "random",
		"Doryani's Machinarium": "random",
		"Mausoleum": "random",
		"Fields": "random",
		"Crater": "random",
		"Coral Ruins": "random",
		"Pillars of Arun": "random",
		"Laboratory": "random",
		"Infested Valley": "random",
		"Moon Temple": "random",
		"The Twilight Temple": "random",
		"Sepulchre": "random",
		"Siege": "random",
		"Belfry": "random",
		"Defiled Cathedral": "random",
		"Summit": "random",
		"Park": "random",
		"Crimson Temple": "random",
		"Dig": "random",
		"Lava Lake": "random",
		"Basilica": "random",
		"Sunken City": "random",
		"Carcass": "random",
		"Desert of Dementia": "random",
		"River of Hysteria": "random",
		"Wastes of Lunacy": "random",
		"Pits of Sorrow": "random",
		"Vaults of Insanity": "random",
		"Halls of Delirium": "random",
		"Manor of Madness": "random",
		"Spires of Delusion": "random",
		"Repository of Derision": "random",
		"Sea of Isolation": "random",
		"Islands of Devastation": "random",
		"Ruins of Despair": "random",
		"Absence of Value and Meaning": "random",
		"Eye of the Storm": "random",
		"Farrul's Den": "random",
		"Craiceann's Cove": "random",
		"Fenumus' Lair": "random",
		"Saqawal's Roost": "random",
		"Domain of Timeless Conflict": "random",
		"Sarn Arena": "random",
		"PvP Arena": "random",
		"PvP Blitz Arena": "random",
		"PetFlats": "random",
		"The Phrecia Outskirts": "random",
		"The Heart of Phrecia": "random",
		"The Lost Cathedral": "random",
		"The Mortal Tomb": "random",
		"The Arachnid Tomb": "random",
		"The Tomb of Statues": "random",
		"The Frozen Abyss": "random",
		"The Simian Cave": "random",
		"The Skeletal Caverns": "random",
		"The Forbidden Ruins": "random",
		"The Vault of the Guardians": "random",
		"The Hall of Heroes": "random",
		"The Desecrated Shrine": "random",
		"The Demonic Shrine": "random",
		"The Infernal Shrine": "random",
		"The Entrance Hall": "random",
		"The Chattering Halls": "random",
		"The Croaking Halls": "random",
		"The Rasping Halls": "random",
		"The Freezing Chamber": "random",
		"The Shrine of the Pagan God": "random",
		"The Dungeon of Anarchy": "random",
		"The Dungeon of Necromancy": "random",
		"The Hollow Cave": "random",
		"The Haunted Dungeon": "random",
		"The Obelisks of Faith": "random",
		"The Burning Cave": "random",
		"The Chamber of Greed": "random",
		"The Cage": "random",
		"The Necromantic Crypt": "random",
		"The Diabolic Crypt": "random",
		"The Misty Cave": "random",
		"The Ember Crypt": "random",
		"The Stormy Ledge": "random",
		"The Frozen Cave": "random",
		"The Glittering Crypt": "random",
		"The Glittering Cave": "random",
		"The Inner Halls Level 1": "random",
		"The Inner Halls Level 2": "random",
		"The Inner Halls Level 3": "random",
		"The Nexus": "random",
		"PvP Capture the Flag": "random",
		"PATH OF EXILE ROYALE": "random",
		"The Endless Ledge": "random",
		"Path of Endurance": "random",
		"Secluded Cove": "random",
		"Crucible of Spirit": "random",
		"Cavernous Hideout": "random",
		"Forsaken Hideout": "random",
		"Bloodsoaked Hideout": "random",
		"Downtown Hideout": "random",
		"Lofty Hideout": "random",
		"Stockroom Hideout": "random",
		"Industrial Hideout": "random",
		"HideoutShip1": "random",
		"Winding Pier": "random",
		"Robber's Trench Hideout": "random",
		"Coral Hideout": "random",
		"Celestial Hideout": "random",
		"Submerged Hideout": "random",
		"Brutal Hideout": "random",
		"Luxurious Hideout": "random",
		"Skeletal Hideout": "random",
		"Stately Hideout": "random",
		"Sunken Hideout": "random",
		"Arboreal Hideout": "random",
		"Shipwreck Hideout": "random",
		"Lush Hideout": "random",
		"Undercity Hideout": "random",
		"Excavated Hideout": "random",
		"Baleful Hideout": "random",
		"Desert Hideout": "random",
		"Towering Hideout": "random",
		"Corrupted Hideout": "random",
		"Innocent Hideout": "random",
		"Shaped Hideout": "random",
		"Furious Hideout": "random",
		"Champion's Hideout": "random",
		"Indomitable Hideout": "random",
		"Morbid Hideout": "random",
		"Eclipsed Hideout": "random",
		"Ravenous Hideout": "random",
		"Cartographer's Hideout": "random",
		"Backstreet Hideout": "random",
		"Coastal Hideout": "random",
		"Unearthed Hideout": "random",
		"Battle-scarred Hideout": "random",
		"Enlightened Hideout": "random",
		"Immaculate Hideout": "random",
		"Overgrown Hideout": "random",
		"Glacial Hideout": "random",
		"Sanguine Hideout": "random",
		"Divided Hideout": "random",
		"Alpine Hideout": "random",
		"Haunted Hideout": "random",
		"Doomguard Hideout": "random",
		"Sunspire Hideout": "random",
		"Glimmerwood Hideout": "random",
		"Celestial Nebula Hideout": "random",
		"Entombed Hideout": "random",
		"Void Hideout": "random",
		"Chiyou Hideout": "random",
		"Lunacy's Watch": "random",
		"Hysteriagate": "random",
		"The Bridge Enraptured": "random",
		"The Syndrome Encampment": "random",
		"Oriath Delusion": "random",
		"The Rogue Harbour": "random",
		"Bunker": "random",
		"Smuggler's Den": "random",
		"Repository": "random",
		"Prohibited Library": "random",
		"Tunnels": "random",
		"Underbelly": "random",
		"Records Office": "random",
		"Mansion": "random",
		"Isolated Sound": "random",
		"Suffocating Fissure": "random",
		"Frozen Springs": "random",
		"Dry Sea": "random",
		"Stagnation": "random",
		"Bramble Valley": "random",
		"Frozen Cabins": "random",
		"Grave Trough": "random",
		"Crimson Township": "random",
		"Forking River": "random",
		"Foundry": "random",
		"Cold River": "random",
		"Forbidden Woods": "random",
		"Silo": "random",
		"Nocturnal Hideout": "random",
		"Primeval Hideout": "random",
		"Ritualist's Hideout": "random",
		"The Maven's Crucible": "random",
		"Absence of Mercy and Empathy": "random",
		"Vaal Reliquary": "random",
		"The Sacred Grove": "random",
		"Crucible Hideout": "random",
		"Hasina Hideout": "random",
		"The Utzaal Arena": "random",
		"The Tower of Ordeals": "random",
		"Beach Landing": "random",
		"Battleground Graves": "random",
		"Karui Wargraves": "random",
		"Bluffs": "random",
		"Rotting Temple": "random",
		"Shipwreck Reef": "random",
		"Sarn Slums": "random",
		"Dried Riverbed": "random",
		"Mountainside": "random",
		"Forest Ruins": "random",
		"Utzaal Outskirts": "random",
		"Desert Ruins": "random",
		"Scrublands": "random",
		"Volcanic Island": "random",
		"Precursor Shrine": "random",
		"Runic Stronghold": "random",
		"Fortified Redoubt": "random",
		"Noxious Gutter": "random",
		"Sandy Vestige": "random",
		"Heroic Tomb": "random",
		"Spectral Hollow": "random",
		"Forgotten Grotto": "random",
		"Mushroom Thicket": "random",
		"Alluring Pool": "random",
		"Lost Sanctum": "random",
		"Chittering Chamber": "random",
		"Drox, The Warlord": "random",
		"Al-Hezmin, The Hunter": "random",
		"Veritania, The Redeemer": "random",
		"Baran, The Crusader": "random",
		"Absence of Symmetry and Harmony": "random",
		"Absence of Patience and Wisdom": "random",
		"Polaric Void": "random",
		"Seething Chyme": "random",
		"Ancestral Hideout": "random",
		"Black Void Hideout": "random",
        "Timekeeper's Hideout": "random",
        "Ghost-lit Graveyard Hideout": "random",
        "Polaric Hideout": "random",
        "Seething Hideout": "random",
        "The Lake of Kalandra": "random",
		"Sanctum Vaults": "random",
		"Sanctum Cathedral": "random",
		"Sanctum Necropolis": "random",
		"Beyond": "random",
		"The Forbidden Sanctum": "random",
		"Sanctum Archives": "random",
		"Sanctum Mausoleum": "random",
		"Your Hideout": "random",
		"Atlas Hideout": "random",
		"Searing Hideout": "random",
		"Tangled Hideout": "random",
		"Your Guild Hideout": "random",
		"Forge of the Titans": "random",
		"Voidborn Reliquary": "random",
        "ExileCon 2023 Hideout": "random",
        "Forge of the Titans Hideout": "random",
        "Ancestral Trial Hideout": "random",
        "The Halls of the Dead": "random",
		"The Viridian Wildwood": "random",
		"Crux of Nothingness": "random",
		"Sanctuary": "random",
		"Citadel": "random",
		"Fortress": "random",
		"Abomination": "random",
		"Ziggurat": "random",
		"The Necropolis": "random",
		"Cosmic Turtle Hideout": "random",
		"Enigma Hideout": "random",
		"Infinite Abyss Hideout": "random",
		"Tavern Hideout": "random"
	}
}  

module.exports = {
	soundtrack: soundtrack
}
